### ISSUE TITLE
编译报错了

### ISSUE THREAD

**Issue by LTaooo** [crazywhalecc/static-php-cli#100]
https://github.com/LTaooo/static-php-cli/actions/runs/5677323403/job/15385442063

![image](https://github.com/crazywhalecc/static-php-cli/assets/28125259/60216092-5507-4c56-b611-58b9f683158b)

**Comment by crazywhalecc** [comment]
似乎是 pgsql 扩展在 Action 上构建有点问题，晚上我在家里的 Linux 机器上试一下。

**Comment by LTaooo** [comment]
好的, 感谢

**Comment by LTaooo** [comment]
> 似乎是 pgsql 扩展在 Action 上构建有点问题，晚上我在家里的 Linux 机器上试一下。

![image](https://github.com/crazywhalecc/static-php-cli/assets/28125259/254da5f8-801f-47cd-97cb-f2119e62ae83)
bcmath不是支持的吗?

**Comment by crazywhalecc** [comment]
bcmatch

> > 似乎是 pgsql 扩展在 Action 上构建有点问题，晚上我在家里的 Linux 机器上试一下。
> 
> ![image](https://user-images.githubusercontent.com/28125259/256466281-254da5f8-801f-47cd-97cb-f2119e62ae83.png) bcmath不是支持的吗?

你的这个 Action 里面的扩展名似乎写错了，应该是 `bcmath`。另外防止写错，可以到文档内使用命令生成器手选：https://static-php-cli.zhamao.me/zh/guide/cli-generator.html

**Comment by crazywhalecc** [comment]
Fixed via #102
