### ISSUE TITLE
micro.sfx可以指定php.ini配置文件吗？

### ISSUE THREAD

**Issue by ikilobyte** [crazywhalecc/static-php-cli#12]
如hyperf需要配置 `swoole.use_shortname='Off' in your php.ini` ，但使用micro.sfx打包成二进制后，不知道如何配置了

**Comment by crazywhalecc** [comment]
Micro.sfx 目前无法指定 `php.ini` 文件，如果修改参数可在项目中使用 `ini_set()`。如果要编译阶段就硬编码参数的话，可在 `sapi/micro/php_micro.c` 中找到 `HARDCODED_INI` 参数插入（CLI 下同理）。

**Comment by ikilobyte** [comment]
好的，感谢

**Comment by try-to** [comment]
php -d swoole.use_shortname=Off bin/hyperf.php start

**Comment by ikilobyte** [comment]
@try-to 是`Micro.sfx`模式下，老哥你搞错了
