### ISSUE TITLE
报错： undefined reference to `micro_get_filename'

### ISSUE THREAD

**Issue by zyccsnow** [crazywhalecc/static-php-cli#140]
/usr/bin/ld: ext/phar/phar.o: in function `phar_compile_file':
/root/static-php-cli/source/php-src/ext/phar/phar.c:3315: undefined reference to `micro_get_filename'

参数：
bin/spc build --build-micro --build-cli "bcmath,calendar,ctype,curl,dba,dom,exif,filter,fileinfo,gd,iconv,mbstring,mbregex,mysqli,mysqlnd,openssl,pcntl,pdo,pdo_mysql,pdo_sqlite,phar,posix,readline,redis,session,simplexml,sockets,sqlite3,tokenizer,xml,xmlreader,xmlwriter,zip,zlib,gmp,shmop,event" -I "memory_limit=1G" --debug

**Comment by crazywhalecc** [comment]
我这边复现不了，可能还需要提供一下编译的 PHP 版本、系统版本等信息。

**Comment by zyccsnow** [comment]
用的是ubuntu22，直接git clone的代码。 刚刚用 
`bin/spc-alpine-docker build --build-cli "bcmath,calendar,ctype,curl,dba,dom,exif,filter,fileinfo,gd,iconv,mbstring,mbregex,mysqli,mysqlnd,openssl,pcntl,pdo,pdo_mysql,pdo_sqlite,phar,posix,readline,redis,session,simplexml,sockets,sqlite3,tokenizer,xml,xmlreader,xmlwriter,zip,zlib,gmp,mongodb,event" -I "memory_limit=1G"`
编译失败，报错内容如下：
`bin/spc-alpine-docker build --build-cli "bcmath,calendar,ctype,curl,dba,dom,exif,filter,fileinfo,gd,iconv,mbstring,mbregex,mysqli,mysqlnd,openssl,pcntl,pdo,pdo_mysql,pdo_sqlite,phar,posix,readline,redis,session,simplexml,sockets,sqlite3,tokenizer,xml,xmlreader,xmlwriter,zip,zlib,gmp,mongodb,event" -I "memory_limit=1G"`

我换下debian再试试看。

**Comment by zyccsnow** [comment]
> 我这边复现不了，可能还需要提供一下编译的 PHP 版本、系统版本等信息。

编译版本是8.1

**Comment by zyccsnow** [comment]
还是同样的报错
有个疑问，我使用webman打包二进制的时候，下载的php8.1.micro.sfx， 但是我用您发布的地址里下载的 micro.sfx 编译后，报错：
`Only run in command line mode`
为什么都是 micro.sfx， 却不大一样

**Comment by crazywhalecc** [comment]
@zyccsnow 如果你之前构建过，最好先删除文件夹 `buildroot` 和 `source` 后重新运行 build 命令（也可以将构建好的 Docker Image 删除后重新构建 Docker Image（例如：`docker rmi cwcc-spc-x86_64`）。

最新的版本提供了一个 MICRO_FAKE_SAPI 的选项，开启后，micro 的 SAPI 将伪装成 cli。因为很多项目会对运行环境进行检查，只能运行在命令行里，所以以前编译的 micro 都是 PHP_SAPI 为 `micro` 的，最新编译的结果加上参数 `--with-micro-fake-cli` 就可以伪装。

另外，环境问题可能是潜在的 Bug 或异常，如果是 Docker 的问题，也可以将构建好的 Docker Image 上报，同时和你编译使用的 static-php-cli 项目目录整个打包上报，帮助发现潜在的问题。

**Comment by zyccsnow** [comment]
可以了 ，今天重新开了个云服务器试了下。  加上--with-micro-fake-cli 之后编译出来的 micro.sfx 能够正常运行 webman 了。 感谢大佬，大佬牛逼
