### ISSUE TITLE
swow v1.0.0发布了，有计划增加swow扩展吗？

### ISSUE THREAD

**Issue by ikilobyte** [crazywhalecc/static-php-cli#17]

**Comment by crazywhalecc** [comment]
有这个计划，目前我熟悉下 swow 的使用先。

**Comment by crazywhalecc** [comment]
说实话 Swow 的文档没好，光看源码和 API 文档我还是对 Swow 迷迷糊糊的，可能得等文档好了。

**Comment by ikilobyte** [comment]
行

**Comment by jingjingxyk** [comment]
昨天刚学的，把目录拷贝php 源码的 ext 目录，然后configiure 启用swow 就行： https://github.com/jingjingxyk/swoole-cli/blob/8b8e0ac4371765d9958ea6dbdcbeb2dcb6aafbc6/library_install_builder_extensions.php#L87

**Comment by crazywhalecc** [comment]
重构版已支持 swow，将关闭此 Issue。
