### ISSUE TITLE
Actons  bug

### ISSUE THREAD

**Issue by tanhongbin-php** [crazywhalecc/static-php-cli#173]
ERROR: failed to solve: process "/bin/sh -c composer update --no-dev" did not complete successfully: exit code: 2
Unable to find image 'cwcc-spc-x86_64:latest' locally
docker: Error response from daemon: pull access denied for cwcc-spc-x86_64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Error: Process completed with exit code 125.

**Comment by crazywhalecc** [comment]
看你资料，我就直接中文了：这个问题应该是由于 Dockerfile 中安装 Alpine 环境下的 PHP 的问题导致的，一会儿我解决一下。

**Comment by tanhongbin-php** [comment]
好的， 大佬，你这速度真快，而且我发现点问题，curl 静态php8.1 使用[walkor] 大佬打包的静态 请求非常慢 都是5秒多，使用很久以前打包的就不会 ，很奇怪

**Comment by crazywhalecc** [comment]
> 好的， 大佬，你这速度真快，而且我发现点问题，curl 静态php8.1 使用[walkor] 大佬打包的静态 请求非常慢 都是5秒多，使用很久以前打包的就不会 ，很奇怪

这个有相关样例文件、编译文件、编译的系统环境等反馈吗，如果可以提供稳定复现的案例和环境可以提供一下，后面新开个 Issue 把这些附上去。

**Comment by crazywhalecc** [comment]
已解决，可以再更新到最新 commit 后试一下重新构建容器使用。

**Comment by tanhongbin-php** [comment]
大佬 又有新问题了 在webman中使用静态php 验证码 Call to undefined function imagettfbbox() gd扩展已经安装了，但是还是报错

**Comment by crazywhalecc** [comment]
> 大佬 又有新问题了 在webman中使用静态php 验证码 Call to undefined function imagettfbbox() gd扩展已经安装了，但是还是报错

你可能用的版本没有把 freetype 库编译进去，这个方法你需要启用 gd 的 freetype 支持才行。static-php-cli 编译 gd 加入 freetype 库的命令参考：

```bash
bin/spc build gd --with-libs=freetype --build-all
```

这个外加可选库的方案可能无法直接使用 Action 编译，可以本地用 Docker 或者原生 Debian 环境下编译，也可以魔改一下 workflow 文件加入它然后在 Action 编译。

**Comment by tanhongbin-php** [comment]
大佬，魔改一下 workflow 文件 这个咋弄

**Comment by crazywhalecc** [comment]
@tanhongbin-php 
![image](https://github.com/crazywhalecc/static-php-cli/assets/20330940/ac256d14-0dc9-40b1-9c97-aa3a255408d2)

**Comment by tanhongbin-php** [comment]
大佬，在反馈一个imagick这个扩展 make[1]: *** [Makefile:8188: utilities/magick] Error 1
make[1]: Leaving directory '/app/source/imagemagick'
make: *** [Makefile:6236: all] Error 2
[06:40:38] [ERRO] Uncaught SPC\exception\RuntimeException: Command run failed with code[2]: cd '/app/source/imagemagick' && make -j2 at /app/src/globals/functions.php(88)
[06:40:38] [ERRO] #0 /app/src/SPC/util/UnixShell.php(44): f_passthru()

**Comment by crazywhalecc** [comment]
imagick 扩展依赖的 imagemagick 现在有点问题，在 Issue #148 已经提到了，后续有时间会解决。

**Comment by tanhongbin-php** [comment]
大佬
workflow 文件 我没找到，难受

**Comment by crazywhalecc** [comment]
![image](https://github.com/crazywhalecc/static-php-cli/assets/20330940/0ffe4be9-264f-40fb-9a03-1b345bc11dbb)

**Comment by tanhongbin-php** [comment]
大佬，现在这个感觉还不成熟呀，又报错了 imagejpeg 函数又没了 ，gd库 都已经有了这是为啥

**Comment by tanhongbin-php** [comment]
![1694505174484(1)](https://github.com/crazywhalecc/static-php-cli/assets/55487039/e979f591-98dc-4654-a01f-4fb4c3c36423)
我是不是应该这样写？

**Comment by tanhongbin-php** [comment]
大佬，我发现问题了 本地构建 的 curl 很卡 非常慢 ，Actions 构建的 gd库 有问题，现在我发现这两个问题，我刚才用8.2.8 的静态[walkor]大佬 构建好的哪个就是这个问题

**Comment by crazywhalecc** [comment]
现在主要是为了面向本地构建可以更灵活而设计的，而且因为大家需要的扩展都不一样，所以默认都是只编译强依赖的库，而 gd 库本身包含的可选依赖比较多，walkor 编译的二进制可能是使用我旧版本（纯 bash 编写的）编译的结果，旧版本没考虑这么多功能和扩展。这里可以根据自己的需要进行选择编译。libjpeg 也不是强依赖，也加入到 `--with-libs` 后即可：`--with-libs=freetype,libjpeg`。`--build-all` 参数不需要在这里写，因为你在那个 Action Trigger 面板上选择对应的编译目标就可以了。

有关 gd 库的这部分可选库，文档中写了：https://static-php-cli.zhamao.me/zh/guide/extension-notes.html#gd
