### ISSUE TITLE
折腾了好几天swoole-cli,为了解决readline，搜到了这里

### ISSUE THREAD

**Issue by jingjingxyk** [crazywhalecc/static-php-cli#18]
666

[ no compile readline ](https://github.com/crazywhalecc/static-php-cli/issues/1)

**Comment by jingjingxyk** [comment]
> 

我先说说我这里遇到的情况

按照着这个是没有问题  https://github.com/swoole/swoole-cli/blob/main/prepare.php

https://github.com/swoole/swoole-cli/blob/72349f242d7bf7b14038d7f03fab0176c23b4988/prepare.php#L267

或者使用如下，也是可以的

```shell
apk add --no-cache  ncurses-dev ncurses-libs ncurses-static
apk add --no-cache  readline readline-dev readline-static

```

但是把ncurses安装在非默认目录，就不行


问题：其实在于ncurses

目前正在参考本项目 ，实验中。待后续反馈

**Comment by crazywhalecc** [comment]
感谢。

另外，此项目还有一个正在重构的版本，那个版本下可以构建 macOS、Windows 和 Linux 三种系统的，理论上来说应该是 lwmbs 项目的一个改进版，但目前还是有很多扩展有问题，所以没有放出来，而且也显然没有支持 readline 扩展。如果你在 readline 编译实验中找到能静态编译出 ncurses 和 readline 库的 configure 和 make 语句，那会是更好的。
