### ISSUE TITLE
Fails when building micro and embed at the same time

### ISSUE THREAD

**Issue by crazywhalecc** [crazywhalecc/static-php-cli#199]
Use command: `bin/spc build mbstring,openssl --build-all --debug`

```
make: *** No rule to make target `install-micro', needed by `install-binaries'.  Stop.
make: *** Waiting for unfinished jobs....
Installing PHP SAPI module:       embed
Installing PHP FPM binary:        /Users/jerry/project/git-project/static-php-cli/buildroot/sbin/
Installing PHP CLI binary:        /Users/jerry/project/git-project/static-php-cli/buildroot/bin/
Installing PHP CLI man page:      /Users/jerry/project/git-project/static-php-cli/buildroot/php/man/man1/
cp: libs/libphp.a: No such file or directory
make: *** [install-sapi] Error 1
Installing PHP FPM defconfig:     /Users/jerry/project/git-project/static-php-cli/buildroot/etc/
Installing PHP FPM man page:      /Users/jerry/project/git-project/static-php-cli/buildroot/php/man/man8/
Installing PHP FPM status page:   /Users/jerry/project/git-project/static-php-cli/buildroot/php/php/fpm/


```

**Comment by crazywhalecc** [comment]
@dunglas Is there a way to build embed SAPI without using `make install`? It seems to affect the final build result. Maybe installing only the libphp part or directly copying the relevant files is a better solution.

**Comment by dunglas** [comment]
Yes, running `make` and copying manually the generated files should be enough (we'll still have to check that `php-config` generated the correct output), but will be hard to maintain. I don't know php-micro but wouldn't be easier and more future-proof to fix its `Makefile`?

**Comment by crazywhalecc** [comment]
@dunglas I modified part of the `Makefile` to support building them simultaneously.
