### ISSUE TITLE
sqlite3 would be useful

### ISSUE THREAD

**Issue by finchss** [crazywhalecc/static-php-cli#2]

**Comment by crazywhalecc** [comment]
I'll try it 😃

**Comment by finchss** [comment]
Managed to get it  in but have to remove the '-    _php_arg="$_php_arg --disable-all" ' sqlite3 has no switch to enable individually.

**Comment by crazywhalecc** [comment]
I will release new scripts and dockerfile for supporting sqlite3 with `--with-sqlite3`

**Comment by crazywhalecc** [comment]
BUT I have no PHP application to try and test statically linked php with sqlite3, release 1.3.2 will contains x86_64 binary only for testing.

**Comment by finchss** [comment]
I have one, will test on that, but generally if the binary runs and reports having the extension available then is fine.

**Comment by crazywhalecc** [comment]
> I have one, will test on that, but generally if the binary runs and reports having the extension available then is fine.

Not always. I recently compiled swoole and php  with raspberrypi zero W, but it compiled successfully and php --ri swoole shows informations.

But when running scripts, it broken.

That's why I test all extensions.
