### ISSUE TITLE
alpine c-ares-static 依赖问题

### ISSUE THREAD

**Issue by xywf221** [crazywhalecc/static-php-cli#20]
目前测试 alpine v3.17 已经移除 c-ares-static包了,需要Dockerfile内指定版本号

**Comment by xywf221** [comment]
[v3.17](https://pkgs.alpinelinux.org/packages?name=c-ares*&branch=v3.17&repo=&arch=x86_64&maintainer=)
[v3.16](https://pkgs.alpinelinux.org/packages?name=c-ares*&branch=v3.17&repo=&arch=x86_64&maintainer=)

**Comment by jingjingxyk** [comment]
用源码包编译吧。 

不过编译安装目录必须是 /usr; 

因为swoole，还需要添加SWOOLE_CFLAGS：  https://github.com/swoole/swoole-src/blob/bdfb22770679ee2fb4b27a5f0d909ce03c25cf6d/config.m4#L468


```shell

./configure --prefix=/usr/ --enable-static --disable-shared 

```

**Comment by crazywhalecc** [comment]
这个纯 bash 版本的 static-php-cli 先就 3.16 的方式替代了，后续重构的版本会将所有依赖库均手工编译并导出 LIC。

**Comment by crazywhalecc** [comment]
还有有关编译安装目录必须是 `/usr` 这个问题其实对于静态编译脚本的项目来说挺头疼的。因为完全用户态的编译最好是可以指定其他目录并且依赖它的项目使用其它目录，不破坏系统。一旦放入 `/usr/` 或者涉及修改系统文件就会造成系统破坏了，这种情况也只能使用 Docker 或 Action 这样的方式无痛编译。

**Comment by jingjingxyk** [comment]
通过实验，这个问题，可以这样解决

编译PHP之前，设置`LIBS`参数

```

export CPPFLAGS=$(pkg-config  --cflags --static  libcares)
export LIBS=$(pkg-config  --libs --static   libcares)

 ./buildconf --force ;
```

实验程序： https://github.com/jingjingxyk/swoole-cli/blob/febd77c42d2d7bd5b7420a9b9f267920d444113c/prepare.php#L920

https://github.com/jingjingxyk/swoole-cli/blob/febd77c42d2d7bd5b7420a9b9f267920d444113c/sapi/make.php#L240
