### ISSUE TITLE
imap support

### ISSUE THREAD

**Issue by crazywhalecc** [crazywhalecc/static-php-cli#202]
@DubbleClick 

> but even that requires a lot of patches both in the form of .patch files as well as replacing contents in files that no .patch file is available for. This project doesn't have any logic to apply patch files yet.

I understand. I tried the patch code in my previous implementation of libmemcached, where I originally planned to put the patch code in the `src/globals/patch/` directory, like this. But in the end, I directly used homebrew's build logic and independent mirror repo, and did not choose patch because it has not been updated for a long time: https://github.com/crazywhalecc/libmemcached-macos

<img width="353" alt="image" src="https://github.com/crazywhalecc/static-php-cli/assets/20330940/721ecddb-c5dc-4df1-9c7a-add411fe0621">

> It also needs multiple services to be running on the system and a (self signed is fine) certificate. It's a complete mess that requires decisions to be taken to integrate it here that I'm not in a position to make.

From the results of my current local testing, it requires at least kerberos, and I'm currently stuck on compiling kerberos. 

Under the existing architecture, it may not be a good idea to use pre-installed dynamic libraries or packages on the system, because this will limit the environment in which spc can run.

**Comment by DubbleClick** [comment]
Kerberos, pop2 (didn't need), pop3 and imap daemons need to be running.

From the uw-imap readme:

```md
4) Update /etc/services to register the pop2 service on TCP port 109, the
   pop3 service on TCP port 110, and the imap service on TCP port 143.  Also
   update Yellow Pages/NIS/NetInfo/etc. if appropriate on your system.

5) Update /etc/inetd.conf (or install files on /etc/xinetd.d) to invoke the
   POP2, POP3, and IMAP daemons on their associated services.

6) If your system uses PAM authentication, be sure to set up /etc/pam.d/imap
   (*not* /etc/pam.d/imapd) and /etc/pam.d/pop (*not* /etc/pam.d/ipop3d or
   /etc/pam.d/pop3d or /etc/pam.d/popd or /etc/pam.d/pop3).

7) Unless you built your system without SSL support, you will need to set
   up SSL server certificates as described in docs/SSLBUILD.
```

Several code pieces have to be patched and the SSLBUILD directory in the Makefile must be changed too.

**Comment by DubbleClick** [comment]
The link you posted in the parent issue was very helpful to get dynamic compilation going: https://github.com/Homebrew/homebrew-core/blob/e7b36de55df0ffeb3bc8a9f7996906a4dd0cc5b8/Formula/imap-uw.rb

**Comment by crazywhalecc** [comment]
I prefer to use the patched repo directly and create a new GitHub repo for it if the library has not been updated for a long time. But if the patched library is relatively new or is still being continuously updated, this patch logic is necessary. If you need this, we can first complete a method to quickly use the patch files in the warehouse.

**Comment by DubbleClick** [comment]
Ok, the library hasn't been updated since 2007 so you will probably prefer a repo with all the patches and necessary changes done.

I would make the SLLINCLUDE directories use environment variables, that way we can specify the directories when we call make.

**Comment by DubbleClick** [comment]
https://github.com/uw-imap/imap

is a mirror with all necessary patches except one to make it work with openssl 3.

**Comment by crazywhalecc** [comment]
You could create a project, it doesn't have to be me. Because now the project also uses a lot of mirror repos, not the original ones.

By the way, would it be better to merge these ancient projects into a GitHub repo and then download it to the same source? WDYT?

In addition, for the current libmemcached extension, because I use the mac-only patched repository, this source code cannot be used directly on Linux. I have not solved this problem yet. How are you going to handle this kind of problem on imap?

**Comment by DubbleClick** [comment]
Sure, I can create the repo. But thinking about it again, if we keep openssl 1.1.1 we can use the github mirror without change.

> By the way, would it be better to merge these ancient projects into a GitHub repo and then download it to the same source? WDYT?

You mean libc-client and uw-imap? I don't have any idea how we could potentially handle pop3d/imapd/kerberos yet. As for libc-client we can use the official mirror I believe because it doesn't need patches.

> In addition, for the current libmemcached extension, because I use the mac-only patched repository, this source code cannot be used directly on Linux. I have not solved this problem yet. How are you going to handle this kind of problem on imap?

I'm not sure I follow? uw-imap compiles in linux too.

**Comment by DubbleClick** [comment]
Running into undefined reference `sigsetjmp` when building this on aarch64.
