### ISSUE TITLE
众人拾柴火焰高

### ISSUE THREAD

**Issue by jingjingxyk** [crazywhalecc/static-php-cli#22]
把步骤这样划分，可好？ 每一步，只干一件事
1. 下载指定版本PHP源码
2. 下载对应版本的扩展
3. 下载扩展对应版本的依赖库
4.  静态编译扩展依赖库
5.  静态编译之前，准备工作
8. 修改相应参数
9. 执行编译
10. 执行构建
11. 打包

不同操作系统，不同cpu架构，都执行一遍上面的流程。
linux macos window + CPU arch  

当然也可以搞一个webUI 把上面展示出来

**Comment by crazywhalecc** [comment]
你提议的这些东西我在我的重构版本就是这么做的，目前做到了可以编译 Linux、macOS 环境的静态二进制，但反而不支持 Swoole 等部分扩展。

重构版我一直在考虑要不要发布，因为和现在用纯 bash 版本写的大相径庭，而且逻辑也不太一样。

**Comment by jingjingxyk** [comment]
这几个项目，实际干的都是同样的事，同时也有自己的特色
https://github.com/crazywhalecc/static-php-cli.git
https://github.com/swoole/swoole-cli.git
https://github.com/jingjingxyk/swoole-cli/blob/dev-pgsql/build-tools-scripts/build-php-no-swoole-cli/build-config-php-8.sh

https://github.com/xywf221/lwmbs.git

https://github.com/dixyes/phpmicro.git

静态编译PHP

**Comment by crazywhalecc** [comment]
是这样的。本项目也只是比较早期因为 swoole 的编译问题才引出来这个项目的，早期迭代过程中也是为了自己的另一个项目方便分发和部署。殊途同归，我希望能有更好的对此类项目的建议，我也愿意吸取其他项目或其他大佬的建议。

**Comment by jingjingxyk** [comment]
swoole-cli里面生成的构建脚本的部分，已经剥离出来 https://github.com/jingjingxyk/swoole-cli/tree/ci 可以尝试一番

  它把： 下载扩展、下载扩展依赖、生成构建脚本、独立出来了，最关键是的，还能生成credits.html

**Comment by ikilobyte** [comment]
项目越来越多人关注了👍🏻

**Comment by jingjingxyk** [comment]
通过源码包编译，依赖库环境已经完成 （借助swoole-ci 项目完成的）

依赖关系：https://github.com/jingjingxyk/swoole-cli/blob/new_dev_build/library_builder.php

创建依赖库安装脚本： https://github.com/jingjingxyk/swoole-cli/blob/new_dev_build/library_install_builder.php



运行已经安装好依赖库的容器环境，跳过安装依赖阶段，直接进入 PHP 运行时构建阶段
```bash

__DIR__=$(
  cd "$(dirname "$0")"
  pwd
)

default_image=registry.cn-beijing.aliyuncs.com/jingjingxyk-public/app:build-swoole-cli-build-dependencies-alpine-edge-20230226T074232Z

 image=$default_image

docker run --rm --name  swoole-cli-build-dev-all-dependencies-container -d -v ${__DIR__}:/work -w /work $image tail -f /dev/null

```

micro 配置： 

https://github.com/jingjingxyk/swoole-cli/blob/new_dev_build/build-tools/php-8/build-config-php-8-micro.sh
https://github.com/jingjingxyk/swoole-cli/blob/new_dev_build/build-tools/php-8/build-make-php-8-micro.sh

![image](https://user-images.githubusercontent.com/6836228/221407807-2dfe0efe-563e-4eb5-899c-d978e307ab56.png)

**Comment by jingjingxyk** [comment]
构建包括的扩展：
```text
curl
iconv
bz2
bcmath
pcntl
filter
session
tokenizer
mbstring
ctype
zlib
zip
posix
sockets
pdo
sqlite3
phar
mysqlnd
mysqli
intl
fileinfo
pdo_mysql
pdo_sqlite
soap
xsl
gmp
exif
sodium
openssl
readline
xml
gd
redis
swoole
yaml
imagick
mongodb
pgsql
pdo_pgsql
apcu
ffi
ds
inotify

```
