### ISSUE TITLE
docker 构建报错

### ISSUE THREAD

**Issue by TNT-ma** [crazywhalecc/static-php-cli#228]
13.74 Executing busybox-1.36.1-r6.trigger
13.75 Executing ca-certificates-20230506-r0.trigger
13.81 OK: 364 MiB in 96 packages
13.92 ln: /usr/bin/php: File exists
------
Dockerfile:3
--------------------
   1 |     FROM alpine:edge
   2 |     RUN echo 'Using original repo'
   3 | >>> RUN apk update;     apk add --no-cache         autoconf         automake         bash         binutils         bison         build-base         cmake         curl         file         flex         g++         gcc         git         jq         libgcc         libstdc++         linux-headers         m4         make         php82         php82-common         php82-pcntl         php82-phar         php82-posix         php82-sodium         php82-tokenizer         php82-dom         php82-xml         php82-xmlwriter         composer         pkgconfig         wget         xz ;   ln -s /usr/bin/php82 /usr/bin/php
   4 |     
   5 |     WORKDIR /app
--------------------
ERROR: failed to solve: process "/bin/sh -c apk update;     apk add --no-cache         autoconf         automake         bash         binutils         bison         build-base         cmake         curl         file         flex         g++         gcc         git         jq         libgcc         libstdc++         linux-headers         m4         make         php82         php82-common         php82-pcntl         php82-phar         php82-posix         php82-sodium         php82-tokenizer         php82-dom         php82-xml         php82-xmlwriter         composer         pkgconfig         wget         xz ;   ln -s /usr/bin/php82 /usr/bin/php" did not complete successfully: exit code: 1
Unable to find image 'cwcc-spc-x86_64:latest' locally
docker: Error response from daemon: pull access denied for cwcc-spc-x86_64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
[root@C20230201158737 static-php-cli]#

**Comment by crazywhalecc** [comment]
如果是 permission denied，建议使用 root 执行、sudo 执行或将当前用户添加到 docker 用户组里。对于 `File exists` 的问题刚修复了，使用最新的 main 分支可以尝试一下。
