### ISSUE TITLE
能增加 gmp 扩展吗

### ISSUE THREAD

**Issue by TNT-ma** [crazywhalecc/static-php-cli#23]
web3 上诸多项目都需要用到gmp扩展函数
能增加一下吗

**Comment by jingjingxyk** [comment]
@TNT-ma  刚才我查看了一下，确实没有配置GMP扩展

查看过程如下：
```bash
 wget https://dl.zhamao.xin/php-bin/file/php-8.1.8-static-bin-x86_64.tar.gz
tar -zxvf php-8.1.8-static-bin-x86_64.tar.gz
mv php php-8.1.8
./php-8.1.8 --ri gmp

```

暂时可以去下载这个（这个包含了gmp扩展） https://github.com/swoole/swoole-src/releases 或者 https://www.swoole.com/download 
暂时先用着呗 ！

**Comment by TNT-ma** [comment]
你的来信我已经收到,我会尽快给你答复！                                         By:小菜鸟

**Comment by crazywhalecc** [comment]
近期会尝试。

**Comment by TNT-ma** [comment]
> @TNT-ma 刚才我查看了一下，确实没有配置GMP扩展
> 
> 查看过程如下：
> 
> ```shell
>  wget https://dl.zhamao.xin/php-bin/file/php-8.1.8-static-bin-x86_64.tar.gz
> tar -zxvf php-8.1.8-static-bin-x86_64.tar.gz
> mv php php-8.1.8
> ./php-8.1.8 --ri gmp
> ```
> 
> 暂时可以去下载这个（这个包含了gmp扩展） https://github.com/swoole/swoole-src/releases 或者 https://www.swoole.com/download 暂时先用着呗 ！
> 
> ![截图 2023-02-02 14-41-53](https://user-images.githubusercontent.com/6836228/216251075-86b1e1df-5a47-43a9-821e-be1442c76858.png)

这个是什么，我还没看懂，我需要 sfx 方便打包 这是一个二进制似乎是PHP文件吧

**Comment by jingjingxyk** [comment]
@TNT-ma  https://github.com/crazywhalecc/static-php-cli/blob/master/README.md   
里面的关键点：  micro  将 PHP 源码和 PHP 二进制构建为一个文件分发！ （意思： micro 默认包含了PHP运行时）

现在把PHP运行时单独拿出来，你就不认识了吗？ 

看这里（存在授权问题），详细请看着里： https://github.com/swoole/swoole-cli/issues/8

**Comment by TNT-ma** [comment]
> 近期会尝试。

如果我自己docker 编译能自己加gmp扩展吗？需要怎么做？

**Comment by jingjingxyk** [comment]
> 

修改Dockerfile 即可

参考：https://www.cnblogs.com/jingjingxyk/p/16841551.html

**Comment by TNT-ma** [comment]
> Dockerfile
看了一下并不懂，等待更新吧。swoole 也没搞懂

**Comment by jingjingxyk** [comment]
运行时+用户应用程序

**Comment by crazywhalecc** [comment]
已在重构版增加。
