### ISSUE TITLE
希望支持 https://pecl.php.net/package/uv 扩展

### ISSUE THREAD

**Issue by wpjscc** [crazywhalecc/static-php-cli#237]
虽然 event 也支持 epoll ,但 uv 在支持 epoll 的基础上，让php有异步读取文件的可能。

https://reactphp.org/event-loop/#extuvloop

https://github.com/reactphp/filesystem#uv

**Comment by tourze** [comment]
希望支持这个，让php的异步处理能力更上一层楼。

**Comment by crazywhalecc** [comment]
已添加，最新 main 分支可构建。
