### ISSUE TITLE
ghrel source pulls pre-releases

### ISSUE THREAD

**Issue by DubbleClick** [crazywhalecc/static-php-cli#239]
example would be icu, pulls 74.1 beta rather than 73.2 stable
or libpng using 16.41 instead of 16.40

**Comment by crazywhalecc** [comment]
We could add `prerelease === false` check here:

https://github.com/crazywhalecc/static-php-cli/blob/dbb566ac7c1adeeed9eb254acb8595f7ba4e03f4/src/SPC/store/Downloader.php#L102C9-L102C9

**Comment by crazywhalecc** [comment]
For libpng, we are currently using the git repository on the libpng official website. Is it necessary to switch to GitHub's `ghtagtar`?

**Comment by DubbleClick** [comment]
Possibly, it certainly doesn't download a tagged version but the current master, which may not be stable.

**Comment by DubbleClick** [comment]
According to libpng website, the official git repos are on sourceforge and github, but the sourceforge one is missing a lot of the newer tags.

It seems like we should switch to ghtag.

**Comment by DubbleClick** [comment]
Never mind, the sourceforge repository also has the new tags, but they are not ordered by time and you can only distinguish releases from betas by the name.

https://github.com/glennrp/libpng/tags seems like the best bet.
