### ISSUE TITLE
编译后使用curl函数时会报错

### ISSUE THREAD

**Issue by TNT-ma** [crazywhalecc/static-php-cli#24]
报错内容：cURL error 77: error setting certificate verify 
-----
项目使用了一个定时自动curl请求第三方地址
正常PHP环境运行 没问题
打包phar后运行·也没有问题
当和php二进制文件组合后报错

**Comment by jingjingxyk** [comment]
@TNT-ma  运行时需要指定 PHP.ini 里面 curl 的证书

**Comment by he426100** [comment]
@jingjingxyk  全都试了，不起作用，还是报错 `SSL certificate problem: unable to get local issuer certificate`，执行`ini_get('curl.cainfo')`返回值是空，`ini_set('curl.cainfo',__DIR__.'/cacert.pem')`会报false

**Comment by jingjingxyk** [comment]
> @jingjingxyk 全都试了，不起作用，还是报错 `SSL certificate problem: unable to get local issuer certificate`，执行`ini_get('curl.cainfo')`返回值是空，`ini_set('curl.cainfo',__DIR__.'/cacert.pem')`会报false

使用软连接这种方式了吗？  ： 大佬给的办法https://github.com/swoole/swoole-cli/issues/88

**Comment by he426100** [comment]
`./swoole-cli  -d 'curl.cainfo="/etc/ssl/cacert.pem"' -d 'openssl.cafile="/etc/ssl/cacert.pem"'  your_application.php`
这个可以

**Comment by TNT-ma** [comment]
> @jingjingxyk 全都试了，不起作用，还是报错 `SSL certificate problem: unable to get local issuer certificate`，执行`ini_get('curl.cainfo')`返回值是空，`ini_set('curl.cainfo',__DIR__.'/cacert.pem')`会报false

这个问题老版本的时候就一直存在，而且我也提过
二进制打包的环境默认curl 使用的整数路径为：/etc/ssl/certs/ca-certificates.crt
-------
而系统自带的整数路径为：/etc/ssl/certs/ca-bundle.crt 和 /etc/ssl/certs/ca-bundle.trust.crt

**解决办法1**
在自己的打包项目内置一个crt，在启动时判断is_file判断/etc/ssl/certs/ca-certificates.crt 文件是否存在
如果不存在则把自己内置的crt文件 复制到：/etc/ssl/certs/ca-certificates.crt


**我的解决办法**
是在启动PHP时 判断了：/etc/ssl/certs/ca-certificates.crt 文件 是否存在
如果不存在则
shell_exec("cp /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt"); 

我的代码是这么写的：
`#CURL证书检查
$crt = "/etc/ssl/certs/ca-certificates.crt";
if(!is_file($crt)){
    if(is_file("/etc/ssl/certs/ca-bundle.crt")){
        shell_exec("cp /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt"); 
    }else if(is_file("/etc/ssl/certs/ca-bundle.trust.crt")){
        shell_exec("cp /etc/ssl/certs/ca-bundle.trust.crt /etc/ssl/certs/ca-certificates.crt"); 
    }
}`

**Comment by crazywhalecc** [comment]
我感觉这个可以通过 patch php-curl 的源码来实现。

**Comment by crazywhalecc** [comment]
现在可以通过在编译时植入硬编码的 php ini 选项进行绑定系统的 cacert 文件了，且 macOS 系统下默认绑定了系统路径的证书。
