### ISSUE TITLE
rename --by-extensions?

### ISSUE THREAD

**Issue by DubbleClick** [crazywhalecc/static-php-cli#242]
Is it just me who `by-extensions` doesn't sit right with?

Maybe something like `--for-extensions` or `--with-extensions` would be better?

**Comment by crazywhalecc** [comment]
As you know, my native language is Chinese, and I don’t understand the complicated English grammar. But when downloading based on the extension name, the downloaded content and the extension may not be the same. At least not `with`, maybe `for` would be more appropriate?

**Comment by DubbleClick** [comment]
I'm not a native English speaker either, so I'm not entirely sure what the best name would be.

I'm also thinking that --for-extensions is better, but I'll ask a friend what he thinks would be the most appropriate name.

**Comment by DubbleClick** [comment]
In their words:

> — Today at 00:07
> Ok I get it
> [00:12]
> You're being dumb for is the clear best word to use
