### ISSUE TITLE
add --with-suggested-exts and --with-suggested-libs switches for build command

### ISSUE THREAD

**Issue by DubbleClick** [crazywhalecc/static-php-cli#243]
It's currently rather annoying to build gd with full type support because we have to specify --with-libs. Theoretically --bloat would also work, but what's the point of building all libs when only a few of them would be used.

Hence I suggest the two switches above - --with-suggested-libs would build every optional library for the selected extensions (i.e. libpng, libjpeg, libwebp and freetype for gd), while --with-suggested-exts would enable all extensions that the selected extensions suggest (i.e. openssl when ldap is built).

I do even believe that maybe they should be considered on by default. Thoughts?

## Tasks

- [ ] add build options `--with-suggested-libs` and `--with-suggested-exts`
- [ ] update docs

**Comment by crazywhalecc** [comment]
I've never made a change in this regard. All extensions and dependencies follow one principle: when it is declared in the Builder, the feature corresponding to this dependency or extension will be enabled.

It sounds like it is feasible to add some commonly used dependencies to the gd compilation options by default, but this will change the existing dependency selection logic. Probably the most complicated part of making this change is how to handle the "commonly used optional" and "uncommonly used optional" sections.

If an extension is almost required to have an optional dependency, I think it can be moved into `lib-depends`. But considering the complex situation mentioned above, I prefer not to change this default behavior for the time being, unless there is a solution that can take into account the above considerations.

**Comment by DubbleClick** [comment]
My idea was that it would rnable *every* suggested library for the extensions selected. I.e. pgsql would build with zlib, zstd, ldap, openssh, etc. and gd would build with all 3 optional libs too.

**Comment by crazywhalecc** [comment]
> if you're not familiar with the project, you build gd and end up not being able to use it since it can't deal with jpegs or fonts

Makes sense. I will let gd include some common libraries by default later, but I may refer to what is included in the version installed by the package management.

**Comment by DubbleClick** [comment]
I don't think we should move them to lib-depends in case someone only wants png support with a tiny executable.

It would be better solved by --with-suggested-libs

**Comment by crazywhalecc** [comment]
I actually have an idea about suggested libraries and extensions. To put it simply, the optional features can be separated out and the enabled status of the features can be printed in a table before compilation. For example, here is an example of how I adapted a feature of the curl library:

https://gist.github.com/crazywhalecc/00abd8a86dfaf69783f3ac91e207d568

Then print two tables before the two seconds of pause in Builder:
1. Print the extension columns to be compiled and the extended feature columns enabled;
2. Print the library list to be compiled and the feature list enabled by the library;

After doing this, you can also turn off a specific feature by passing in parameters when compiling a library that is currently added. (I have a headache about naming it, and I don’t know if this should be called a “feature”)

This idea is also a solution I thought about during early refactoring, but doing so may require changing the build method of each library and extension, which amounts to a major disruptive update. I am not sure whether this is necessary.

**Comment by DubbleClick** [comment]
The printing part is a great idea - I don't think we should be calling them "features" though, as they really are libraries that we build with. `--with-libs` is fine the way it is, all we should do is a convenient `--with-suggested-libs` switch. I will create a possible implementation of the option after the c++ branch is merged.
