### ISSUE TITLE
求教一个问题在正常的PHP中：PHP_BINARY 函数问题

### ISSUE THREAD

**Issue by TNT-ma** [crazywhalecc/static-php-cli#258]
在正常的PHP环境中：
PHP_BINARY 函数可以获得 当前PHP解释器的可执行文件路径比如：/www/server/php/80/bin/php
那么再PHP二进制 和 micro.sfx 时如何处理这个问题

**Comment by crazywhalecc** [comment]
micro.sfx 中这个应该默认为空。参见 [phpmicro wiki](https://github.com/easysoft/phpmicro/wiki/How-PHPmicro-work#%E5%85%A8%E5%B1%80%E5%8F%98%E9%87%8F)。

可以通过手动指定 INI 来设置这个值：`micro.php_binary=xxxxx`
