### ISSUE TITLE
编译.sfx后，用在 webman 编译二进制后 运行提示：Only run in command line mode 

### ISSUE THREAD

**Issue by TNT-ma** [crazywhalecc/static-php-cli#259]
这是什么原因造成的？

**Comment by crazywhalecc** [comment]
webman检查了 SAPI 的名称，只允许在 cli 的 SAPI 下运行的。有两种方案：

1. 将 webman 的 SAPI 检查部分加上 `micro`。
2. 编译 micro.sfx 时构建命令加上 `--with-micro-fake-cli` 选项，将 micro 伪装为 cli SAPI。

**Comment by TNT-ma** [comment]
在官方找到答案了 正在尝试打包，
我看到webman 作者 提供的那个扩展列表里面get_loaded_extensions 打印出来有：core date json 等扩展（你的CLI 编译命令生成器 似乎没有这3个选择 请问是内置了吗？）

**Comment by crazywhalecc** [comment]
core 是每个 PHP 必存在的扩展，date 扩展也默认被包含在了基础的 PHP 编译中。json 扩展在 8.0 及以后版本都是默认包含的，无需手动启用，使用 spc 编译 PHP 7.4 及以下版本时也会默认自动启用。
