### ISSUE TITLE
Add retry for download command

### ISSUE THREAD

**Issue by crazywhalecc** [crazywhalecc/static-php-cli#261]

**Comment by jingjingxyk** [comment]
提示：  github action  runner  环境里，gmp 库已经无法下载成功了。 即便是多次重试也是不行的。

具体原因：  github action  runner 的 IP 因 DDOS 攻击，被 gmp 源站 屏蔽了。

详情:  https://gmplib.org/

**Comment by crazywhalecc** [comment]
> github action runner 环境里，gmp 库已经无法下载成功了。

目前 main 分支已使用 GitHub 镜像仓库下载，虽然不是最新版，但目前没有什么问题。
