### ISSUE TITLE
imagettfbbox(): Could not find/open font

### ISSUE THREAD

**Issue by TNT-ma** [crazywhalecc/static-php-cli#268]
imagettfbbox(): Could not find/open font
这个报错是 gd 的那个扩展引起的？ 正常PHP环境没问题，二进制报错

**Comment by crazywhalecc** [comment]
有最小复现代码段吗？顺便需要提供下编译的命令。

**Comment by TNT-ma** [comment]
编译命令：
`bin/spc build --with-libs=freetype,libjpeg,libavif,libwebp --with-micro-fake-cli --build-micro "openssl,sqlite3,zlib,bcmath,calendar,ctype,curl,dom,sockets,event,ffi,fileinfo,filter,gd,gmp,iconv,mbstring,session,redis,pcntl,posix,phar,pdo,pdo_mysql,exif,xml,xmlreader,xmlwriter,zip,soap,mysqlnd"`

复现代码的轮子：
https://packagist.org/packages/endroid/qr-code

大概就是生成二维码，渲染文字时，设置字体

我通过GPT查阅 应该不是二进制原因？意思是系统缺少字体吗：
`这个错误通常表示 PHP 的 GD 库无法找到指定的 TrueType 字体文件。要解决这个问题，你需要确保你的字体文件路径是正确的，并且 PHP 能够访问到这个文件`

**Comment by crazywhalecc** [comment]
看你添加了 freetype，那应该不是编译静态 php 的问题。我记得 gd 使用字体文件确实挺麻烦的，好几个地方需要使用不同的相对路径。GPT 说的应该没错。
