### ISSUE TITLE
freetype is buggy for bulk(huge)

### ISSUE THREAD

**Issue by crazywhalecc** [crazywhalecc/static-php-cli#274]
https://github.com/static-php/static-php-cli-hosted/actions/runs/6976443903/job/18984901031

**Comment by jingjingxyk** [comment]
缺少依赖而已：
```bash 
 autogen.sh: 1: libtoolize: not found

```
详见：
https://github.com/static-php/static-php-cli-hosted/actions/runs/6976443903/job/18984901031#step:8:21660
