### ISSUE TITLE
postgresql bug in bulk build for macOS x86_64

### ISSUE THREAD

**Issue by crazywhalecc** [crazywhalecc/static-php-cli#278]
https://github.com/crazywhalecc/static-php-cli/actions/runs/7021969669/job/19105273004
https://github.com/static-php/static-php-cli-hosted/actions/runs/7005398391/job/19055781716

**Comment by jingjingxyk** [comment]
问题出在： 链接到系统库了 ，更详细的信息，需要到源码包里 ` build`  目录里看 `config.log ` 文件

从构建错误里，就能看出，这些不正常，比如 ： ` -I/include`    `-L/lib`   `  -lgnutls`   这些链接肯定是不对的

本项目并没有配置  `gnutls`  

```bash 

CPPFLAGS="-I/Users/runner/work/static-php-cli/static-php-cli/buildroot/include -I/include -I/Users/runner/work/static-php-cli/static-php-cli/buildroot/lib/pkgconfig/../..//include/libxml2 -I/Users/runner/work/static-php-cli/static-php-cli/buildroot/include"

 LDFLAGS="-L/Users/runner/work/static-php-cli/static-php-cli/buildroot/lib -L/lib -L/Users/runner/work/static-php-cli/static-php-cli/buildroot/lib/pkgconfig/../..//lib -L/Users/runner/work/static-php-cli/static-php-cli/buildroot/lib"  

LIBS="-lssl -lcrypto -lz -lreadline -lncurses -lz -lzstd -lldap -lgmp -lresolv -lgnutls -llber -lgmp -lresolv -lxslt -lxml2 -licudata -licui18n -licuuc -lz -liconv -lm -licui18n -licuuc -licudata -lpthread -lm -lc++"

```


解决办法： 构建脚本之前添加 如下配置，（指定多个有分号分隔即可）

```bash

export PKG_CONFIG_PATH=/Users/runner/work/static-php-cli/static-php-cli/buildroot/lib/pkgconfig/Users/runner/work/static-php-cli/static-php-cli/buildroot/usr/lib/pkgconfig

```

**Comment by jingjingxyk** [comment]
需要排查某个库的 `library.pc`  配置文件，配置文件里的地址不正确


排查方法： 执行如下命令看输出结果

```bash 
export PKG_CONFIG_PATH=/Users/runner/work/static-php-cli/static-php-cli/buildroot/lib/pkgconfig

pkg-config  --cflags-only-I --static   penssl zlib readline libxml-2.0 zlib

pkg-config  --cflags-only-I --static  libzstd  ldap libxslt  icu-i18n



```

**Comment by crazywhalecc** [comment]
@jingjingxyk 非常感谢。另外，有关 #273 问题，可能需要涉及到 postgresql 的新版本更新，目前我还没有看这个更新要改什么，但似乎有些 patch 是硬编码 15.1 版本的，升级 postgresql 版本可能需要修改这些和版本强相关的 patch。

**Comment by jingjingxyk** [comment]
找到了：  https://github.com/crazywhalecc/static-php-cli/actions/runs/7029574813/job/19127437855#step:8:18357

`[08:29:15] [INFO] -lldap -lgmp -lresolv -lgnutls -llber -lgmp -lresolv`

 ldap 的静态构建需要  解决  `pkg-config.pc`  文件的生成


```bash

[08:29:15] [INFO] [EXEC] pkg-config --cflags-only-I  --static ldap
[08:29:15] [INFO] -I/Users/runner/work/static-php-cli/static-php-cli/buildroot/include
[08:29:15] [INFO] [EXEC] pkg-config --libs-only-L    --static ldap
[08:29:15] [INFO] -L/Users/runner/work/static-php-cli/static-php-cli/buildroot/lib
[08:29:15] [INFO] [EXEC] pkg-config --libs-only-l    --static ldap
[08:29:15] [INFO] -lldap -lgmp -lresolv -lgnutls -llber -lgmp -lresolv

```

**Comment by jingjingxyk** [comment]
> @jingjingxyk 非常感谢。另外，有关 #273 问题，可能需要涉及到 postgresql 的新版本更新，目前我还没有看这个更新要改什么，但似乎有些 patch 是硬编码 15.1 版本的，升级 postgresql 版本可能需要修改这些和版本强相关的 patch。

解决硬编码应该去完善  https://github.com/postgres/postgres.git     libpq 静态构建

**Comment by crazywhalecc** [comment]
> 解决硬编码应该去完善 https://github.com/postgres/postgres.git libpq 静态构建 ，v16 开始使用 meson 作为构建选项

这应该不好办了，好像现在 pgsql 的维护者还坚持不支持静态编译。

**Comment by crazywhalecc** [comment]
The final conclusion reached: The reason why pgsql cannot be compiled on macOS x86_64 has nothing to do with pgsql itself. The problem is broken down into several recent related issues and PRs. Now main branch can compile pgsql normally.

- #279 updated `postgresql` version `15.1` -> `16.1`.
- This issue actually caused by #280 and #285 .
