### ISSUE TITLE
gd 扩展无法在 Actions 构建

### ISSUE THREAD

**Issue by tanhongbin-php** [crazywhalecc/static-php-cli#282]
[04:24:27] [ERRO] Uncaught SPC\exception\RuntimeException: Command run failed with code[1]: cd '/app/source/freetype' && sh autogen.sh at /app/src/globals/functions.php(89)
[04:24:27] [ERRO] #0 /app/src/SPC/util/UnixShell.php(44): f_passthru()
#1 /app/src/SPC/builder/unix/library/freetype.php(29): SPC\util\UnixShell->exec()
#2 /app/src/SPC/builder/LibraryBase.php(143): SPC\builder\linux\library\freetype->build()
#3 /app/src/SPC/builder/LibraryBase.php(150): SPC\builder\LibraryBase->tryBuild()
#4 /app/src/SPC/builder/BuilderBase.php(88): SPC\builder\LibraryBase->tryBuild()
#5 /app/src/SPC/command/BuildCliCommand.php(80): SPC\builder\BuilderBase->buildLibs()
#6 /app/src/SPC/command/BaseCommand.php(83): SPC\command\BuildCliCommand->handle()
#7 /app/vendor/symfony/console/Command/Command.php(326): SPC\command\BaseCommand->execute()
#8 /app/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#9 /app/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#10 /app/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#11 /app/bin/spc(15): Symfony\Component\Console\Application->run()
#12 {main}
Error: Process completed with exit code 1.
大佬，咱能把这个gd扩展的包补全嘛，现在一直报错 我都不知道怎么搞了

**Comment by crazywhalecc** [comment]
麻烦贴一下编译的 Action 地址，我后面会集中处理一波现在编译的 Issue。

**Comment by crazywhalecc** [comment]
是的。

**Comment by tanhongbin-php** [comment]
您看看吧，我都生产使用哈 我们公司 webman准备都使用这个静态php 就看这个现在生产验证码 gd库的问题了，剩下没遇到啥问题

**Comment by crazywhalecc** [comment]
我最近在处理工作上的 ddl，过段时间才能统一处理这些问题。

另外，刚才的问题我简单看了下，可能是由于 freetype 使用了 libtoolize，而默认的 Docker 中没有安装。你可以尝试临时调整一下 `bin/spc-alpine-docker` 中的 `apk add` 命令，增加 `libtool`，然后再尝试使用 Actions 构建。

相关文件：https://github.com/crazywhalecc/static-php-cli/blob/c1758bd75466a36a0c86d8efc72f4002003e5787/bin/spc-alpine-docker#L76C20-L76C20

**Comment by jingjingxyk** [comment]
@tanhongbin-php 
这里有现成的静态库参考例子： https://github.com/jingjingxyk/swoole-cli/blob/build_native_php/sapi/src/builder/extension/gd.php  你把它搬过来，稍微改动一番即可。

https://github.com/jingjingxyk/swoole-cli/blob/build_native_php/sapi/src/builder/library/libjpeg.php
https://github.com/jingjingxyk/swoole-cli/blob/build_native_php/sapi/src/builder/library/libpng.php
https://github.com/jingjingxyk/swoole-cli/blob/build_native_php/sapi/src/builder/library/libwebp.php
https://github.com/jingjingxyk/swoole-cli/blob/build_native_php/sapi/src/builder/library/freetype.php

https://github.com/jingjingxyk/swoole-cli/blob/build_native_php/sapi/src/builder/library/libavif.php
https://github.com/jingjingxyk/swoole-cli/blob/build_native_php/sapi/src/builder/library/libgav1.php
https://github.com/jingjingxyk/swoole-cli/blob/build_native_php/sapi/src/builder/library/svt_av1.php
https://github.com/jingjingxyk/swoole-cli/blob/build_native_php/sapi/src/builder/library/aom.php

**Comment by tanhongbin-php** [comment]
我先都试试看看哈，感谢两个大佬

**Comment by TNT-ma** [comment]
已测试加入：libtool \  后还是不行
