### ISSUE TITLE
这个新的分支和以前旧的分支构建上有什么区别吗？

### ISSUE THREAD

**Issue by TNT-ma** [crazywhalecc/static-php-cli#283]
同样的代码 同样的扩展
使用老版本的分支构建的 webman  打包后可以正常运行
使用新版本的分支构建的 webman  打包后有部分函数不报错但是无法执行。

是php.ini 上面有啥区别吗？为什么会如此。也没有什么特殊函数就是：hex2bin  hash 之类的。

**Comment by TNT-ma** [comment]
是因为新的这个没有hash 扩展吗？

**Comment by crazywhalecc** [comment]
你说的老版本的分支是指的 bash-version 还是 refactor？

区别还是挺大的，不过是对于支持的扩展、依赖库编译方式的区别，最终编译的结果还是要取决于编译到里面的扩展和库。

麻烦提供下旧版本、新版本编译的分支、spc 版本、PHP 版本、编译的扩展列表、操作系统、架构，这样可以更准确地定位问题。

**Comment by TNT-ma** [comment]
webman作者fork你的老版本那个可以正常使用
`https://github.com/walkor/static-php-cli`

新的static-php-cli 编译的不能使用
编译代码：
`bin/spc build --with-libs=freetype,libjpeg,libavif,libwebp --with-micro-fake-cli --build-micro "openssl,sqlite3,zlib,bcmath,calendar,ctype,curl,dom,sockets,event,ffi,fileinfo,filter,gd,gmp,iconv,mbstring,session,redis,pcntl,posix,phar,pdo,pdo_mysql,exif,xml,xmlreader,xmlwriter,zip,soap,mysqlnd"`

在使用以下轮子调用时新的编译的无法使用：
`https://github.com/kornrunner/php-secp256k1/blob/main/src/Secp256k1.php`
我看了基本上是一些gmp hash bin hex 之类的函数  

非常奇怪debian10  debian12  无法用  debian11  ubuntu  centos正常

**Comment by crazywhalecc** [comment]
不报错无法执行有什么特征吗？我在本地的 Debian 12 环境按照你的命令编译，并运行没有问题（执行了 `hex2bin` 函数）。

另外你说的是使用环境还是编译环境？

**Comment by TNT-ma** [comment]
> 不报错无法执行有什么特征吗？我在本地的 Debian 12 环境按照你的命令编译，并运行没有问题（执行了 `hex2bin` 函数）。
> 
> 另外你说的是使用环境还是编译环境？

使用环境。

**Comment by crazywhalecc** [comment]
编译环境是什么呢？

**Comment by TNT-ma** [comment]
> 编译环境是什么呢？

`CentOS Stream 9 x86_64`

**Comment by TNT-ma** [comment]
还有个问题 现在默认 
`git clone https://github.com/crazywhalecc/static-php-cli.git --depth=1`
然后当执行：
`composer update`

要求的PHP 版本最低都是 PHP8.1  ，那么我本地如果是PHP8.1 而我打包时选择8.0  这样确定没有问题吗？

我的项目是基于PHP8.0的

**Comment by crazywhalecc** [comment]
PHP 8.1 只是 static-php-cli 自身的运行环境要求，你就把这个当作一个别的语言写的项目也可以（比如假想它是 go 写的，和 PHP 无关），它只是编译 PHP 的工具。至于要编译哪个版本的 PHP 静态二进制，和运行 spc 的环境无关。

我在下载 CentOS 镜像，晚些在虚拟机里试一下是什么情况。

**Comment by TNT-ma** [comment]
> PHP 8.1 只是 static-php-cli 自身的运行环境要求，你就把这个当作一个别的语言写的项目也可以（比如假想它是 go 写的，和 PHP 无关），它只是编译 PHP 的工具。至于要编译哪个版本的 PHP 静态二进制，和运行 spc 的环境无关。
> 
> 我在下载 CentOS 镜像，晚些在虚拟机里试一下是什么情况。

需要我提供一个 phar 包（或者一份PHP源代码）给你测试吗？ 
我昨天搞了1天都没找到原因，我使用的是 webman  自身的那个：php8.micro.sfx  进行打包没问题（但是由于缺少gmp扩展会报错）但是第一句代码执行了的
而使用自己构建的第一句代码 无法执行也没有报错信息很奇怪

**Comment by crazywhalecc** [comment]
有的话更好。不过使用 micro.sfx 在过多扩展加入后执行出现一些 Bug 也有可能，之前看 WorkerMan 论坛提到过，我自己也在特定环境中遇到过。

**Comment by TNT-ma** [comment]
> 有的话更好。不过使用 micro.sfx 在过多扩展加入后执行出现一些 Bug 也有可能，之前看 WorkerMan 论坛提到过，我自己也在特定环境中遇到过。

我尝试使用 bin/spc-alpine-docker构建 来测试看看是不是有问题 但是遇到了错误：
`[06:48:26] [CRIT] Build failed with SPC\exception\RuntimeException: Command run failed with code[1]: cd '/app/source/freetype' && sh autogen.sh 1>/dev/null 2>&1
[06:48:26] [CRIT] Please check with --debug option to see more details.`

这是什么原因是没有安装 freetype 吗 如何安装

**Comment by crazywhalecc** [comment]
freetype 是这个问题，我一会儿会修复，合并到 main。

https://github.com/crazywhalecc/static-php-cli/issues/282#issuecomment-1846570910

**Comment by crazywhalecc** [comment]
那就开 `--debug` 看一下具体的报错。

**Comment by TNT-ma** [comment]
我给你提供了一个测试包 phar包 和 源代码
https://github.com/TNT-ma/microceshi

**Comment by crazywhalecc** [comment]
我在本地无法成功复现，你有能成功复现的 micro.sfx 吗？

我刚才克隆了这个仓库，然后在 Docker 内根据上面命令编译了一个 micro 二进制，然后结合，运行后可以正常执行。

**Comment by TNT-ma** [comment]
> 我在本地无法成功复现，你有能成功复现的 micro.sfx 吗？
> 
> 我刚才克隆了这个仓库，然后在 Docker 内根据上面命令编译了一个 micro 二进制，然后结合，运行后可以正常执行。

我找了1天终于找到原因了，原因是gmp扩展的问题
`gmp_mul 和  gmp_add`

我不确定是不是我打包时的 环境问题，如果你有可以正常执行的 micro  可以提供一下给我 测试一下吗？

**Comment by crazywhalecc** [comment]
这个是我在 Debian 12（x86_64）使用 `musl-toolchain` 编译的：[micro.sfx.zip](https://github.com/crazywhalecc/static-php-cli/files/13627785/micro.sfx.zip)

**Comment by TNT-ma** [comment]
我马上测试一下

**Comment by TNT-ma** [comment]
> 这个是我在 Debian 12（x86_64）使用 `musl-toolchain` 编译的：[micro.sfx.zip](https://github.com/crazywhalecc/static-php-cli/files/13627785/micro.sfx.zip)
> 
> 补充：这个是使用 `bin/spc-alpine-docker` 构建的：[micro.sfx_docker.zip](https://github.com/crazywhalecc/static-php-cli/files/13627799/micro.sfx_docker.zip)

2个版本均进行了测试 ，都不行。

**Comment by crazywhalecc** [comment]
有什么报错或者非预期行为？

**Comment by TNT-ma** [comment]
> 有什么报错或者非预期行为？

 没有任何报错，我使用的系统是 debian 10
`worker[webman:32542] exit with status 4`

逐行代码我都使用：echo 标记，如下  终端只输出到X6 就断了，网页响应状态码为502：

`function Tdecode($base58Address) {
    bcscale(0);
    echo "A1\n";
    $alphabet = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
    echo "A2\n";
    $base = strlen($alphabet);
    echo "A3\n";
    $decoded = gmp_init(0);
    echo "A4\n";

    $length = strlen($base58Address);
    for ($i = 0; $i < $length; $i++) {
        echo "X5\n";
        $value = strpos($alphabet, $base58Address[$i]);
        echo "X6\n";
        $decoded = bcmul($decoded, $base); 
        echo $decoded;
        echo "X7\n";
        $decoded = bcadd($decoded, $value); 
        echo "X8 \n";
    }
echo "A9\n";
    $hexAddress = gmp_strval($decoded, 16);
    echo "A10\n";
     return substr($hexAddress, 0, -8); 
}`

**Comment by TNT-ma** [comment]
> crazywhalecc

我给你的邮箱发送了一台复现问题的 服务器 你可以测试看看，这个问题我折腾了很久无法解决

**Comment by crazywhalecc** [comment]
Illegal instruction 问题，这个和 Linux 底层有关系了，可能需要编译一个带调试符号的版本调试一下。

**Comment by TNT-ma** [comment]
> Illegal instruction 问题，这个和 Linux 底层有关系了，可能需要编译一个带调试符号的版本调试一下。

如果是Linux 底层问题，那么为什么同一个服务器，我使用：PHP test.php 没问题， 它们之间互相底层不一样吗？

而且：bcmul  和  gmp_mul  是相同作用的函数我都试过了不行！

并且 在debian 12 ，ubuntu20，centos 7.8 上都不行，但是某个debian12 又可以。我真是百思不得其解

**Comment by TNT-ma** [comment]
我又从阿里云开了3台 服务器测试：
debian10  debian11  debian12  可以运行 
腾讯云开了1台
debian10 不行。。 使用系统自身的PHP环境全部可以运行 

按理如果是系统底层上的问题，是不是应该使用：php test.php  也不能运行才对吧？

**Comment by crazywhalecc** [comment]
> 按理如果是系统底层上的问题，是不是应该使用：php test.php 也不能运行才对吧？

不一定，因为 SAPI 不一样。理论上，你不可以把 micro SAPI 完全当作 cli 环境，因为二者运行原理不同（虽然现在的各种方式都努力把 micro 当作一个合并的 cli 来的）。

另外，使用系统的 PHP 和使用 `spc` 编译的 PHP-cli 也不一样，至少编译参数和优化参数肯定用得不一样，所以使用系统的 PHP cli 环境来对比没有参考性。

**Comment by TNT-ma** [comment]
那看来 sapi 还是不太成熟。
