### ISSUE TITLE
是否支持libwebp，--with-webp编译选项

### ISSUE THREAD

**Issue by Endy-c** [crazywhalecc/static-php-cli#286]

**Comment by crazywhalecc** [comment]
如果你要编译 gd 的 webp 支持，可以在编译时使用命令参数 `--with-libs=libwebp` 增加 webp 的支持。因为 libwebp 和 gd 的 webp 是可选特性，所以默认不会包含它。

例如，构建一个包含 openssl、gd、mbstring 扩展的 php-cli 并带有 webp、freetype 支持：`bin/spc build openssl,gd,mbstring --with-libs=libwebp,freetype --build-cli`。

如果是使用 GH Actions 构建，需要修改下构建的 yml，在编译命令中加入 `--with-libs` 参数。

**Comment by Endy-c** [comment]
下载了nghttp2，但curl的编译选项里-DUSE_NGHTTP2=OFF

**Comment by Endy-c** [comment]
加了--with-libs=nghttp2
./configure --enable-static --disable-shared --host=x86_64-unknown-linux --enable-lib-only --with-boost=no ZLIB_CFLAGS="-I/software/spc/buildroot/include" ZLIB_LIBS="/software/spc/buildroot/lib/libz.a" OPENSSL_CFLAGS="-I/software/spc/buildroot/include" OPENSSL_LIBS="/software/spc/buildroot/lib/libssl.a /software/spc/buildroot/lib/libcrypto.a /software/spc/buildroot/lib/libz.a" LIBXML2_CFLAGS="-I/software/spc/buildroot/include" LIBXML2_LIBS="/software/spc/buildroot/lib/libxml2.a /software/spc/buildroot/lib/libicui18n.a /software/spc/buildroot/lib/libicuio.a /software/spc/buildroot/lib/libicuuc.a /software/spc/buildroot/lib/libicudata.a /software/spc/buildroot/lib/libz.a /software/spc/buildroot/lib/libiconv.a /software/spc/buildroot/lib/libcharset.a" --with-libev=no --with-libcares=no --with-libngtcp2=no --with-libnghttp3=no --with-libbpf=no --with-libevent-openssl=no --with-jansson=no --with-jemalloc=no --with-systemd=no --with-cunit=no --prefix=
编译选项里--with-libnghttp3=no希望更改成yes，应该如何调节
