### ISSUE TITLE
[CRIT] Source [pkg-config] not downloaded or not locked, you should download it first !

### ISSUE THREAD

**Issue by CViniciusSDias** [crazywhalecc/static-php-cli#288]
When I try to run `./spc build ffi,mbstring,sodium --build-micro -I "ffi.enable=true"` I get the following error:

> [CRIT] Source [pkg-config] not downloaded or not locked, you should download it first !

There are no instructions in the documentation on how/where I should download the source. I tryied cloning [the repository](https://gitlab.freedesktop.org/pkg-config/pkg-config/) into `source` folder, tried adding the binary to `buildroot/bin`, but nothing worked.

I tried to use the GitHub Actions built micro, but I get the following error when trying to execute:

> Fatal error: Uncaught FFI\Exception: FFI API is restricted by "ffi.enable" configuration directive

I assume it's because `ffi.enable` needs to be `true` instead of `preload`, but I'm unnable to set it without building it myself, and I'm unnable to build it, unfortunately.

**Comment by crazywhalecc** [comment]
> When I try to run ./spc build ffi,mbstring,sodium --build-micro -I "ffi.enable=true" I get the following error:

- Download all sources command (with different PHP version): `./spc download --all --with-php=8.3`
- Download sources for extensions and dependencies: `./spc download --for-extensions=ffi,mbstring,sodium`

> I tried to use the GitHub Actions built micro, but I get the following error when trying to execute:

Now Linux is purely statically compiled, and it cannot support methods such as ffi/dl and other dynamic linking methods for other libraries. If you are using macOS micro, you can use ffi and dl. 

> I assume it's because ffi.enable needs to be true instead of preload

The `-I` parameter to specify the required ini config when compiling or combining micro.sfx.

> I tryied cloning [the repository](https://gitlab.freedesktop.org/pkg-config/pkg-config/) into source folder

I just noticed this problem too. It seems that the freedesktop.org website is down. I have copied a previous source code archive to dl.static-php.dev, I'm working on #64 right now and will merge it soon, which contains the address to modify the pkgconfig download.

**Comment by CViniciusSDias** [comment]
> Now Linux is purely statically compiled, and it cannot support methods such as ffi/dl and other dynamic linking methods for other libraries. If you are using macOS micro, you can use ffi and dl.

I don't think I understood this correctly.

If I can't correctly use FFI, should it be "yes" [here](https://static-php.dev/en/guide/extensions.html)?

**Comment by CViniciusSDias** [comment]
I was able to build and create the standalone file, but I got into the FFI error you mentioned:

> Fatal error: Uncaught FFI\Exception: Failed loading 'libtcl8.6.so' (Dynamic loading not supported)

Is there a way around it? 😳

**Comment by crazywhalecc** [comment]
> If I can't correctly use FFI, should it be "yes" [here](https://static-php.dev/en/guide/extensions.html)?

You didn't mention what type of operating system you are using (Linux or macOS), so I explained the different features of different systems.

To put it simply, currently only static-php under macOS can use ffi/dl, and Linux cannot.

**Comment by CViniciusSDias** [comment]
> You didn't mention what type of operating system you are using

I'm sorry. It's Linux.

> To put it simply, currently only static-php under macOS can use ffi/dl, and Linux cannot.

So [this](https://static-php.dev/en/guide/extensions.html) should say "no" on the ffi line for Linux column, right?

**Comment by crazywhalecc** [comment]
> So [this](https://static-php.dev/en/guide/extensions.html) should say "no" on the ffi line for Linux column, right?

For linux, no.

**Comment by CViniciusSDias** [comment]
> For linux, no.

"no" as in it should not say "no"? Even though you just mentioned it doesn't work? 🤔

**Comment by CViniciusSDias** [comment]
> but it will not be considered at this time.

That's my point: The doc should say that FFI for Linux isn't supported, right?

**Comment by crazywhalecc** [comment]
To be precise, it doesn't work, but it can be supported. Because ffi itself can be compiled inline into PHP, it means that it is supported, but it is another matter that it cannot be used. This has something to do with the limitations of the Linux kernel and has nothing to do with PHP.

But you're right, I shouldn't describe linux ffi as yes without any comments inside the documentation.

**Comment by crazywhalecc** [comment]
The documentation will be updated. https://github.com/static-php/static-php-cli-docs/pull/7
