### ISSUE TITLE
error shown when using the built in composer and php

### ISSUE THREAD

**Issue by abbychau** [crazywhalecc/static-php-cli#289]
![image](https://github.com/crazywhalecc/static-php-cli/assets/350283/e3e87218-9145-450f-bfa9-cedf67585f15)

**Comment by crazywhalecc** [comment]
The latest dev-dependencies of static-php-cli currently require the sodium extension, and the `common` combination php-cli downloaded by `bin/setup-runtime` (from dl.static-php.dev) does not contain this extension.

I will fix this later, or you can temporarily modify `setup-runtime` to download the `bulk` combination and `8.2.13`.

https://github.com/crazywhalecc/static-php-cli/blob/cf198e0f0a4133dd62bcce79ea4e7932b45abd4f/bin/setup-runtime#L28
