### ISSUE TITLE
Redis compression and serializer options not enabled in phpredis

### ISSUE THREAD

**Issue by binaryfire** [crazywhalecc/static-php-cli#293]
`phpredis` supports compression and serialization. This is configured using constants like `Redis::COMPRESSION_LZ4` and `Redis::SERIALIZER_IGBINARY`, for example:

```
// database.php in Laravel

    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX'),
            'compression' => Redis::COMPRESSION_LZ4,
            'serializer' => Redis::SERIALIZER_IGBINARY,
        ],
        .........
```

This feature isn't supported in the version of `phpredis` compiled by static-php-cli, which causes problems like this: https://github.com/laravel/octane/issues/789

CC: @dunglas

**Comment by crazywhalecc** [comment]
The next update, I will attempt to include them. The support for lz4 requires static compilation of liblz4, and igbinary serializer needs static compilation of igbinary. The good news is that static compilation of these two libraries should be straightforward.

**Comment by crazywhalecc** [comment]
Now the main branch has added igbinary and liblz4! @binaryfire @dunglas 

Currently, igbinary is an independent extension and liblz4 is a library. If you want to enable igbinary support for redis, please add the igbinary extension when compiling (for example: `build redis,igbinary`). If you want to enable lz4 support, use `--with-libs=liblz4` to add additional libraries when compiling.
