### ISSUE TITLE
Unable to Build PHP Static with GitHub Actions - [CRIT] ext [igbinary] is not supported yet

### ISSUE THREAD

**Issue by macosupdate** [crazywhalecc/static-php-cli#300]
I am currently facing an issue while attempting to build PHP static using GitHub Actions (CI on x86_64 linux ). The specific error message encountered is as follows:

> [CRIT] ext [igbinary] is not supported yet

extensions: "bcmath,calendar,curl,dom,exif,fileinfo,filter,iconv,igbinary,imagick,intl,mbstring,mysqli,mysqlnd,opcache,openssl,pdo,pdo_sqlite,shmop,simplexml,sodium,sqlite3,xml,xmlreader,zip,zlib"

php version: fpm 7.4 and fpm 8.2

**Comment by crazywhalecc** [comment]
It seems that the problem is caused by GitHub Actions Cache. It is recommended to manually delete all caches before trying again.
