### ISSUE TITLE
大佬，actions构建的 apcu 扩展 如何把apc.enable_cli=1写入php.ini里面，我应该改那个文件呢？

### ISSUE THREAD

**Issue by tanhongbin-php** [crazywhalecc/static-php-cli#302]
apcu 扩展  现在使用不了发现是 apc.enable_cli=1 模式是=0的，就是关闭，现在需要开启，actions构建的，现在是webman框架在代码中没有办法加入 isi_set 不生效，有啥好办法嘛？

**Comment by crazywhalecc** [comment]
https://github.com/crazywhalecc/static-php-cli/blob/5c7552f8260cbba98a75dab8117a3ecfdd2d990c/.github/workflows/build-linux-x86_64.yml#L79C38-L79C38

在这里添加 `-I "apc.enable_cli=1"` 参数，可以在编译时候硬编码这条 ini 到 php 二进制中。
