### ISSUE TITLE
Bulk build failed: libxml2 with icu

### ISSUE THREAD

**Issue by crazywhalecc** [crazywhalecc/static-php-cli#303]
https://github.com/static-php/static-php-cli-hosted/actions/runs/7392878476/job/20111972935

**Comment by jingjingxyk** [comment]
解决办法：
办法一：直接把 libxml2 依赖 ICU选项 禁用 ；` -DCMAKE_DISABLE_FIND_PACKAGE_ICU=ON`
办法二：引用 ICU 库时，liubxml2 库 设置 ` -DCMAKE_PREFIX_PATH="{$icu_install_dir}" `  设置多个使用分号隔开
办法三：设置  `-DICU_ROOT={$icu_install_dir} `  或者   `-DICU_DIR={$icu_install_dir} `   
办法四： 设置` -DICU_INCLUDE_DIR={$icu_install_dir}/include  -DICU_LIBRARY={$icu_install_dir}/lib/`
办法五： 修改libxml2 cmake 配置文件
