### ISSUE TITLE
Sorry for English! Are builds working for macOS?

### ISSUE THREAD

**Issue by simonhamp** [crazywhalecc/static-php-cli#31]
I'm running an M1 Mac, but I can't get any of the downloads from the download server to run on my machine. Also all of the build artifacts have expired on github.

I will set up to build myself, I just wanted to try it out first

**Comment by crazywhalecc** [comment]
M1 Mac is running macOS(kernel called darwin), not linux, and current master branch is an old version, which only supports the compilation of binaries for Linux environments.

I'm rebuilding this project. The new version will support statically compiled binaries of macOS and Windows. But it is a big project, I need to debug every library needed for compilation. In a word, the new version has not been released yet. See discussion #29 .

But if you are interested in this project, I can compile a macOS static binary using my MacBook. Please provide the extensions you need to use.

**Comment by simonhamp** [comment]
Thanks for replying in English 🙏

I'm very interested in the project and happy to support your efforts to bring about this new version. Are you accepting sponsorship anywhere?

I'd love for there to be a set of portable and reliable PHP executables!

Extensions I'm using:
- curl
- redis
- mbstring
- openssl
- ftp (`--enable-ftp`)
- gd
- pcntl (`--enable-pcntl`)
- pdo with sqlite (I think this is enabled by default)

**Comment by crazywhalecc** [comment]
Thanks. I have tried these extensions on mac, and some extensions are not implemented, such as sqlite (required by pdo_sqlite), ftp, mbstring.

And I compiled a binary with `curl,redis,openssl,gd,pcntl`. By the way, openssl may not work well, because the binary does not contain any ssl certificates.

Because the API of the macOS system is always changing, and Mach-O binary cannot be compiled into a pure static file, the binary I compiled may not work on your mac. Your test will help me a lot.

[php.zip](https://github.com/crazywhalecc/static-php-cli/files/10982238/php.zip)

**Comment by crazywhalecc** [comment]
Thank you for supporting this project, but I currently have no account to receive international sponsorship. Maybe I will create one in the future. I would be more happy if someone could provide optimization for this project.

**Comment by simonhamp** [comment]
It works! This is brilliant.

I think it's quite critical to have access to SSL certificates as `curl` is kind of useless without that. What would it take to do that?

And for my needs, SQLite would be the most important thing after that.

With those things in place, I think we'd have a pretty functional distributable PHP binary.

If there's anything I can do to help you, please let me know.

**Comment by jingjingxyk** [comment]
不就说curl 没有配置证书嘛,那就配置一下，运行时配置就可以了

example : 
```bash
mkdir -p /tmp/ssl/

wget https://curl.se/ca/cacert.pem  -O /tmp/ssl//cacert.pem

php  -d "curl.cainfo= "/home/jingjingxyk/ssl/cacert.pem"   your_application.php 

# or
echo '"curl.cainfo="/home/jingjingxyk/ssl/cacert.pem"' > /tmp/my_custom.ini

php -c  /tmp/my_custom.ini  your_application.php 

```

```php
$ca=" /tmp/ssl//cacert.pem";
ini_set('curl.cainfo', $real_path);
ini_set('openssl.cafile', $real_path);

```

more :  https://www.php.net/manual/en/curl.configuration.php#ini.curl.cainfo

**Comment by simonhamp** [comment]
Ok, so I'm getting `Error:Protocol "https" not supported or disabled in libcurl` and when I check out `php -i` for this binary, I see the following for `curl`, where SSL and Multi SSL are disabled:
![Screenshot 2023-03-16 at 10 16 50](https://user-images.githubusercontent.com/31628/225586519-b56ccbb3-c427-40ac-a04c-9a91312b4580.png)

So I don't think it's necessarily a lack of certificates that's preventing it connecting - at least that doesn't appear to be the immediate issue (maybe it will be a problem after this is resolved?).

**Comment by crazywhalecc** [comment]
Oh, I found a bug. It just a compile order problem. I need to compile openssl at first in order to enable ssl in curl extension.

[php.zip](https://github.com/crazywhalecc/static-php-cli/files/10989661/php.zip)

**Comment by jingjingxyk** [comment]
@crazywhalecc  可参考这里哈，最近几天刚完成的

https://github.com/swoole/swoole-cli/blob/main/conf.d/curl.php

brotli : https://github.com/swoole/swoole-cli/pull/71/files

**Comment by crazywhalecc** [comment]
> @crazywhalecc 可参考这里哈，最近几天刚完成的
> 
> https://github.com/swoole/swoole-cli/blob/main/conf.d/curl.php
> 
> brotli : https://github.com/swoole/swoole-cli/pull/71/files

感谢，不过我目前还在调试一些别的东西，最近工作也比较忙，这些问题后续有时间再处理。这个项目如果你有意愿参与的话，我可以在完成框架后邀请你加入本项目，后续可以采用 PR 互审方式更新。

**Comment by simonhamp** [comment]
@crazywhalecc that latest build works fine with SSL on my M1 (my test was basic `curl https://example.com`)

So for me, it would just be the PDO + SQLite that's needed now. Please let me know if there's anything I can do to help

**Comment by crazywhalecc** [comment]
Now I have built a binary with sqlite3 extension, but pdo_sqlite extension has a linking issue. This is a strange problem, and I haven't found a solution yet.

**Comment by crazywhalecc** [comment]
@simonhamp Solved. Now with pdo_sqlite. 

[php.zip](https://github.com/crazywhalecc/static-php-cli/files/11001565/php.zip)

**Comment by crazywhalecc** [comment]
Now refactor branch has supprted sqlite3 and pdo_sqlite.

**Comment by simonhamp** [comment]
Thanks for this, I hope to try it this week.

I'd love to know more about how you set this up so I can run these builds myself

**Comment by crazywhalecc** [comment]
> Thanks for this, I hope to try it this week.
> 
> I'd love to know more about how you set this up so I can run these builds myself

For mac, just use homebrew install this package first: `['make', 'bison', 'flex', 'pkg-config', 'git', 'autoconf', 'automake', 'tar', 'unzip', 'xz', 'gzip', 'bzip2', 'cmake']`. And don't forget install `php`.

To setup static-php-cli, `git clone https://github.com/crazywhalecc/static-php-cli.git --branch=refactor`, `composer update`.

1. Fetch resources: `bin/spc fetch --all`
2. Build static php binary with extensions: `bin/spc build sqlite3,ftp,curl,openssl,tokenizer,bcmath`
3. Build phpmicro binary with extensions, just add `--build-micro` or `--build-all` option.
4. If anything goes wrong, add `--debug` option or send me feedback here.
5. Source archive or git repo will be downloaded at `downloads/`, lib source will be extracted at `source/`, required libraries will be compiled to `buildroot/`, and final php binary path will tell you in terminal.

**Comment by simonhamp** [comment]
@crazywhalecc just want to say how awesome this is. I've managed to get builds running on my Mac with no trouble!

I'm still trying to get the right extensions installed, but this is a huge leap. Thank you 🙏
