### ISSUE TITLE
imagick 和 swoole 同时编译报错，去掉 lib.json 中 brotli 的 `-static` 后缀就可以正常编译了

### ISSUE THREAD

**Issue by minbaby** [crazywhalecc/static-php-cli#311]
报错如下：
```
copying selected object files to avoid basename conflicts...
x86_64-linux-musl-ar: MagickCore/.libs/libMagickCore-7.Q16HDRI.lax/lt15-libbrotlidec-static.a: No such file or directory
make[1]: *** [Makefile:7213: MagickCore/libMagickCore-7.Q16HDRI.la] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/min-work/code/php/static-php-dev/static-php-cli/source/imagemagick'
make: *** [Makefile:6242: all] Error 2

   SPC\exception\RuntimeException

  Command run failed with code[2]: cd '/home/min-work/code/php/static-php-dev/static-php-cli/source/imagemagick' && make -j16
```

当我把 `lib.json` 中 `brotli` 的 `*-static.a` 中的 `static` 去掉之后就可以正常编译了，所以咨询一下这个地方是出于什么考虑添加的 `-static` 后缀

![image](https://github.com/crazywhalecc/static-php-cli/assets/3191858/ca477cb9-666e-4691-a3d6-dca84668f098)

![image](https://github.com/crazywhalecc/static-php-cli/assets/3191858/3d7d1eef-75c8-43c5-b90f-7671cd608bb4)

**Comment by crazywhalecc** [comment]
我昨天也遇到了这个问题，主要原因是 `ln -sf` 会让 imagemagick 编译脚本拷贝库文件时出错，所以在 #310 中我也修复了这个问题。这个问题主要是由于之前用的 `--target=brotlicommon-static` 生成的 `libbrotlicommon-static.a`，后面使用了 `--target=brotlicommon` 后面删除 `.so` 和 `.dylib` 的方式。其实使用不带 `static` 是没问题的。

**Comment by minbaby** [comment]
这问题最核心的问题就是 `swoole` 扩展启用了 `brotli`, 然后 `imagick` 依赖的 `freetype` 也 依赖了 `brotli`。在不启用 `brotli`的时候就可以正常编译
