### ISSUE TITLE
[FEATURE] support for pecl extensions

### ISSUE THREAD

**Issue by pintend** [crazywhalecc/static-php-cli#330]
ability to compile with extensions from pecl e.g. sqlsrv and pdo_sqlsrv 

would it be possible to compile with the odbc driver using `--with-libs`?

**Comment by crazywhalecc** [comment]
We already support the `sqlsrv` extension (based on the unixodbc library) on macOS and Linux, and pdo_sqlsrv can also be added, after my vacation is over.
​
