### ISSUE TITLE
之前的版本不维护了吗？一直在用能否加个sg13 或14扩展啊

### ISSUE THREAD

**Issue by TNT-ma** [crazywhalecc/static-php-cli#34]
我现在一直用的之前版本挺好使的,
折腾了2天的sg13 怎么都没搞上去，能不能更新一次支持以下

**Comment by TNT-ma** [comment]
> > 重构版目前太多扩展未被支持了 无法用于生产环境
> 
> 有哪些是需要支持的，列出来的话会优先考虑加。重新构建一个版本需要考虑的东西比较多。
> 
> > 我现在一直用的之前版本挺好使的,
> > 折腾了2天的sg13 怎么都没搞上去，能不能更新一次支持以下
> 
> SG 现在支持静态编译 Loader 了吗，你在 bash-version 分支是怎么使用 SG Loader的？

能指导一下吗？我搞那个  swoole_loader  也没成功 哎妈呀真蛋疼

**Comment by jingjingxyk** [comment]
sg13  是啥？

**Comment by TNT-ma** [comment]
> sg13 是啥？ 全称是啥？

SourceGuardian 宝塔面板扩展列表默认是SG11 最新是SG14

**Comment by crazywhalecc** [comment]
@TNT-ma SG 的扩展默认都是提供的 .lin 格式的，实际文件类型其实就是一个 .so 类型的动态加载库。它默认依赖了 glibc，而静态 php 是依赖 musl-libc 的。我不知道你之前是怎么在 bash-version 下编译的静态 php 使用 sg，如果旧版本成功使用了，也请提供一个使用它的方式，好确定到底是什么问题。因为新版本理论上和旧版本编译出来的东西别无二致。

**Comment by TNT-ma** [comment]
> @TNT-ma SG 的扩展默认都是提供的 .lin 格式的，实际文件类型就是一个 .so 类型的动态加载库，类似传统编译 PHP 方式并加载 pecl 扩展。它默认依赖了 glibc，而静态 php 是依赖 musl-libc 的。我不知道你之前是怎么在 bash-version 下编译的静态 php 使用 sg，如果旧版本成功使用了，也请提供一个使用它的方式，好确定到底是什么问题。

就是未成功 ... 我是说我在使用旧版本的 sfx ，但是想在sfx上增多一个 SG 扩展 未成功
---
我在想比如：swoole_loader  加密（固定linux系统）
我是否可以直接在编译sfx时 ，php.ini 中指定一个固定目录路径的 so 扩展（举例：/etc/swoole_loader.so）
然后我的PHP代码启动时，判断/etc/swoole_loader.so文件是否存在，如果不存在则把我代码目录下的swoole_loader.so 移动至：/etc/swoole_loader.so

这样模式是否也能成功加载第三方扩展？

**Comment by crazywhalecc** [comment]
@TNT-ma 重构版本没有编译 libffi 进去，libffi 是用于加载动态库的库。如果需要此特性的话，近期会加上。

**Comment by TNT-ma** [comment]
> @TNT-ma 重构版本没有编译 libffi 进去，libffi 是用于加载动态库的库。如果需要此特性的话，近期会加上。

重构版本 目前看样子并不适合生产环境，
我的项目依赖诸多扩展：curl event gd openssl pcntl sockets gmp
我看其中好几个都未实验过。，

**Comment by crazywhalecc** [comment]
untested 意思是可以编译上去，理论上可以正常运行，但未实际在项目中调用扩展相关函数进行测试。其中除了 openssl，curl 之外其他几个你提到的都是可以编译的。

**Comment by crazywhalecc** [comment]
是这样的，我只有在调试的差不多的时候，例如任何人可以 fork 本仓库使用新版构建，且列表中提到的主流扩展都可以正常使用的时候就会将重构分支切换到主分支。当前的情况还是有很多不足。

**Comment by TNT-ma** [comment]
> glibc



> @TNT-ma SG 的扩展默认都是提供的 .lin 格式的，实际文件类型就是一个 .so 类型的动态加载库，类似传统编译 PHP 方式并加载 pecl 扩展。它默认依赖了 glibc，而静态 php 是依赖 musl-libc 的。我不知道你之前是怎么在 bash-version 下编译的静态 php 使用 sg，如果旧版本成功使用了，也请提供一个使用它的方式，好确定到底是什么问题。

想这种是否有可能把 .so 给打包到PHP二进制文件里面(不执行)加个if 啥的判断X目录是否存在，然后输出到X目录，并在php.ini中加载这个库？ 有没有这种玩法的可能？

**Comment by crazywhalecc** [comment]
phpmicro 支持一个魔法的 ini 头，可以将部分 php.ini 的键值信息硬编码到 micro.sfx 内。你可以通过这种方式设置 ini。

**Comment by TNT-ma** [comment]
> phpmicro 支持一个魔法的 ini 头，可以将部分 php.ini 的键值信息硬编码到 micro.sfx 内。你可以通过这种方式设置 ini。[INI-Setting](https://github.com/easysoft/phpmicro/wiki/INI-settings)

特地去试了一下让其魔法头加载 so 收到提示：
Warning: PHP Startup: Unable to load dynamic library
(Dynamic loading not supported)
(Dynamic loading not supported)) in Unknown on line 0

**Comment by TNT-ma** [comment]
> phpmicro 支持一个魔法的 ini 头，可以将部分 php.ini 的键值信息硬编码到 micro.sfx 内。你可以通过这种方式设置 ini。[INI-Setting](https://github.com/easysoft/phpmicro/wiki/INI-settings)

PHPmicro的坑
linux的C库实现上并没有考虑静态/静态PIE文件的libdl功能，因此目前linux的PHPmicro并不能使用FFI相关函数，通过自定义的ld脚本和对C库小修改或许可以实现（Windows下FFI工作正常）。

**Comment by crazywhalecc** [comment]
@TNT-ma 是这样的，所以 Linux 下编译为纯静态的时候，libffi 是无法正常工作的，所以我也不知道你之前是怎么运行起来 SG 的。目前我能掌握的信息就是，lwmbs 项目支持了 glibc 的动态二进制编译，基于 glibc 的 php 单文件理论上是可以支持 dl 加载。但这样就和本项目是不相干的内容了，理论上讲只依赖 glibc 也可以算作单一二进制，但 Linux 的 glibc 并不是唯一，也就不是纯静态的二进制，所以这里就暂时没有考虑。

**Comment by TNT-ma** [comment]
> @TNT-ma 是这样的，所以 Linux 下编译为纯静态的时候，libffi 是无法正常工作的，所以我也不知道你之前是怎么运行起来 SG 的。目前我能掌握的信息就是，lwmbs 项目支持了 glibc 的动态二进制编译，基于 glibc 的 php 单文件理论上是可以支持 dl 加载。但这样就和本项目是不相干的内容了，理论上讲只依赖 glibc 也可以算作单一二进制，但 Linux 的 glibc 并不是唯一，也就不是纯静态的二进制，所以这里就暂时没有考虑。

我没有运行起来,我说的是我一直在用旧的分支的 sfx,用在了生产环境!现在是想使用sg 或者 swoole loader之类的加密扩展,遇到了问题 🥲唉 看来如果用二进制环境 是无解了,翻遍了文档都没找到任何方法可以加载动态库,

**Comment by crazywhalecc** [comment]
从保护源码的角度来讲，其实项目采用 PHP 编写且想要保护源码，SG 是一种成熟且折中的方案。首先，SG Loader 我们没有源码，而且是商业软件，不属于开源的范畴。你说的需求和本项目可解决的方案不同。理论上你可以打包一个 `.deb`，`.rpm`，将动态链接的 PHP 和 SG Loader、Swoole Compiler 一起打包成 Linux 发行版的软件包，这样更适合你所描述的需求，而不是静态二进制。

**Comment by TNT-ma** [comment]
> 

哎折腾了许久这些东西 好不容易把项目彻底重写完美使用静态方式运行，到最后发现扩展加密不行。，真是吐血，到最后一场空  我草。。只能等了，等PHPmicro 支持动态加载扩展。

**Comment by crazywhalecc** [comment]
理论上静态 PHP 和你项目重写的关系其实并不大，只要项目是基于 CLI 架构的，使用静态 PHP 和动态 PHP 应该是一样的。phpmicro 也只是一个自执行的 Archive 模式。

加密扩展因为不开放源码，无法使用 in-tree 方式加载到 PHP 的编译二进制中，这是一个关键的问题。如果想在 Linux 引入动态库，则只能让 PHP 不能完全静态链接，也就是动态编译方式。另外，因为 mac 和 Windows 的特性，如果你想在 macOS、Windows 编译并引入 SG Loader，理论上没有问题。我近期也会尝试在 Linux 编译基于 glibc 的单个二进制，但此项计划仅为测试，应该不会并入主线特性。

**Comment by TNT-ma** [comment]
> 理论上静态 PHP 和你项目重写的关系其实并不大，只要项目是基于 CLI 架构的，使用静态 PHP 和动态 PHP 应该是一样的。phpmicro 也只是一个自执行的 Archive 模式，支不支持加载动态库取决于编译出来的 micro 或 php-cli 的链接方式以及是否引入了 libffi。
> 
> 加密扩展因为不开放源码，无法使用 in-tree 方式加载到 PHP 的编译二进制中，这是一个关键的问题。如果想在 Linux 引入动态库，则只能让 PHP 不能完全静态链接，也就是动态编译方式。当然，除非 SourceGuardian 官方提供了一个 .a 版本支持 in-tree 构建的 Linux Loader，目前还不能在纯静态中引入一个动态库。
> 
> 另外，因为 mac 和 Windows 的特性，如果你想在 macOS、Windows 编译并引入 SG Loader，理论上没有问题。我近期也会尝试在 Linux 编译基于 glibc 的单个二进制，但此项计划仅为测试，应该不会并入主线特性。

我在：[phpmicro](https://github.com/easysoft/phpmicro)  项目看到编译时分：--enable-micro=all-static 静态  和 --enable-micro 动态  ，咱这个项目如果直接把静态 改成 动态编译 能成功吗 😃

**Comment by crazywhalecc** [comment]
成功是可以成功，但是要注意，本项目是 **static-php-cli**，所以每处代码都是在努力向静态编译靠拢。所以再回到动态链接就变得没有意义。动态链接的话就需要依赖系统的 glibc、ld-linux 库了，就对系统的运行环境有了要求。

**Comment by crazywhalecc** [comment]
现在 macOS 可以改改就能做到加载 sg loader 扩展，但 Linux 目前还是没得办法，需要改动太多了。

**Comment by TNT-ma** [comment]
> 现在 macOS 可以改改就能做到加载 sg loader 扩展，但 Linux 目前还是没得办法，需要改动太多了。

说真的macos 我个人理解压根用不上这玩意，真正开发项目的人如果是为了本地开发那么压根不介意安装个PHP环境，搞打包的最终目的都是为了项目编译为一个文件分发，但是目前无法加载一些第三方扩展，就很受限制。

**Comment by crazywhalecc** [comment]
> 说真的macos 我个人理解压根用不上这玩意，真正开发项目的人如果是为了本地开发那么压根不介意安装个PHP环境，搞打包的最终目的都是为了项目编译为一个文件分发，但是目前无法加载一些第三方扩展，就很受限制。

static-php-cli 如果只能用来跑 server 端程序，那就比较普通了。目前有国外大佬使用本项目做出来了可以用 PHP/Laravel 编写的桌面 App：https://twitter.com/marcelpociot/status/1643562290942205952

**Comment by TNT-ma** [comment]
> > 说真的macos 我个人理解压根用不上这玩意，真正开发项目的人如果是为了本地开发那么压根不介意安装个PHP环境，搞打包的最终目的都是为了项目编译为一个文件分发，但是目前无法加载一些第三方扩展，就很受限制。
> 
> static-php-cli 如果只能用来跑 server 端程序，或者认为在 macOS 仅仅是个开发环境，其实想象力还不够丰富。目前有国外大佬使用本项目做出来了可以用 PHP/Laravel 编写的桌面 App：https://twitter.com/marcelpociot/status/1643562290942205952
> 
> 理论上说 PHP 作为一个 C 语言程序，可以有很丰富的跨平台特性和扩展性，正如我一开始学习 PHP 的时候，就没有写过一行 fpm 的代码，都是 CLI 环境，搞 MC 服务器、Linux/macOS 命令行工具、Swoole 等。它可以做的事情有很多，而 static 编译的给了不同平台更多的可能。

假设需要做一个桌面应用的情况下，系统层的权限申请验证  Hook API调用 或者注入  这些应该PHP无解吧？ 毕竟只是个脚本语言
