### ISSUE TITLE
【feature】 support webview GUI extension

### ISSUE THREAD

**Issue by KingBes** [crazywhalecc/static-php-cli#342]
> 一个用于 C/C++ 的小型跨平台 Web 视图库，用于构建现代跨平台 GUI。
该项目的目标是为最广泛使用的平台创建一个通用的 HTML5 UI 抽象层。
它支持双向 JavaScript 绑定（从 C/C++ 调用 JavaScript 和从 JavaScript 调用 C/C++）。

他的github：https://github.com/0hr/php-webview

**Comment by crazywhalecc** [comment]
这个调用方式没有编译 webview 库，同时它也不是 PHP 扩展形式，而是调用了 FFI，无法在 Linux 系统中使用它，暂时不支持。如果有人将 webview 的接口 port 到 PHP 扩展，也许会可能支持。、

另外，如果你是在 macOS 系统上，使用 spc 编译时加入 `ffi` 扩展，并下载相应系统的 webview 库，理论上应该可以使用。其他系统暂时不支持。
