### ISSUE TITLE
Musl toolchains: gcc 13.2 works with --enable-static-pie

### ISSUE THREAD

**Issue by DubbleClick** [crazywhalecc/static-php-cli#345]
See title, fixes the segmentation fault in the `intl` extension that we previously got when building with default-pie.
```console
[root@localhost php-src]# ./sapi/cli/php --ri intl

intl

Internationalization support => enabled
ICU version => 74.2
ICU Data version => 74.2
ICU TZData version => 2023c
ICU Unicode version => 15.1

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => Off => Off
```

In order to build a 13.2 toolchain, add a `gcc-13.2.0.tar.xz.sha1` in the `hashes` folder. Contents of the file:

```
5f95b6d042fb37d45c6cbebfc91decfbc4fb493c  gcc-13.2.0.tar.xz
```

then update the config.mak to 13.2 and rebuild.

**Comment by DubbleClick** [comment]
There's an issue when building static-php, though, where it throws segmentation faults during the php-src ./configure command. Building from the command line with pkg_config specified works just fine however, so I have no idea what the issue is. Unfortunately I don't have the free capacity at work to investigate, at the moment.
 
https://github.com/php/php-src/issues/12442#issuecomment-1952144087

**Comment by crazywhalecc** [comment]
I have no clue at the moment. Is this an issue with the musl-toolchain?

**Comment by DubbleClick** [comment]
Not necessarily. We built the musl toolchains without --enable-default-pie (which makes gcc build position independent code by default, this is the default behaviour for every linux distro).

So right now, spc produces php executables without position independent code. This is not necessarily a problem, they still work, but PIEs are recommended for extra security.

Updating the toolchain to 13.2 gcc with `--enable-default-pie` in the config.mak means that spc will build position independent php. We just had to remove the arg for 11.4 because it lead to crashes with the intl extension.

**Comment by DubbleClick** [comment]
To sum up: not required, but recommended. Not urgent.

**Comment by crazywhalecc** [comment]
Seems `make TARGET=x86_64-linux-musl -j` just works without `sed -i 's/poison calloc/poison/g' ./gcc-13.2.0/gcc/system.h`.

**Comment by crazywhalecc** [comment]
**config.mak**:

```
STAT = -static --static
FLAG = -g0 -Os -Wno-error

ifneq ($(NATIVE),)
COMMON_CONFIG += CC="$(HOST)-gcc ${STAT}" CXX="$(HOST)-g++ ${STAT}"   
else
COMMON_CONFIG += CC="gcc ${STAT}" CXX="g++ ${STAT}"
endif

COMMON_CONFIG += CFLAGS="${FLAG}" CXXFLAGS="${FLAG}" LDFLAGS="${STAT}"

BINUTILS_CONFIG += --enable-gold=yes --enable-gprofng=no
GCC_CONFIG += --enable-static-pie --disable-cet --enable-default-pie  
#--enable-default-pie

CONFIG_SUB_REV = 888c8e3d5f7b
GCC_VER = 13.2.0
BINUTILS_VER = 2.40
MUSL_VER = 1.2.4
GMP_VER = 6.2.1
MPC_VER = 1.2.1
MPFR_VER = 4.2.0

LINUX_VER = 6.1.36
```

**Dockerfile.aarch64**:

```dockerfile
FROM alpine:edge

RUN apk add --no-cache \
gcc g++ git make curl perl \
rsync patch wget libtool \
texinfo autoconf automake \
bison tar xz bzip2 zlib \
file binutils flex \
linux-headers libintl \
gettext gettext-dev icu-libs pkgconf \
pkgconfig icu-dev bash \
ccache libarchive-tools zip

WORKDIR /opt

RUN git clone https://git.zv.io/toolchains/musl-cross-make.git
WORKDIR /opt/musl-cross-make
COPY config.mak /opt/musl-cross-make
COPY gcc-13.2.0.tar.xz.sha1 /opt/musl-cross-make/hashes

RUN make TARGET=aarch64-linux-musl -j || :
RUN sed -i 's/poison calloc/poison/g' ./gcc-13.2.0/gcc/system.h
RUN make TARGET=aarch64-linux-musl -j
RUN make TARGET=aarch64-linux-musl install -j
RUN tar cvzf aarch64-musl-toolchain.tgz output/*
```

**gcc-13.2.0.tar.xz.sha1**:

```
5f95b6d042fb37d45c6cbebfc91decfbc4fb493c  gcc-13.2.0.tar.xz
```

**Comment by crazywhalecc** [comment]
Updated and tested: 

- https://dl.static-php.dev/static-php-cli/deps/musl-toolchain/x86_64-musl-toolchain.tgz
- - https://dl.static-php.dev/static-php-cli/deps/musl-toolchain/aarch64-musl-toolchain.tgz
