### ISSUE TITLE
macbook上使用SPC构建报错

### ISSUE THREAD

**Issue by y1713375484** [crazywhalecc/static-php-cli#352]
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [xsltproc] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
[08:14:20] [ERRO] Uncaught SPC\exception\RuntimeException: Command run failed with code[2]: cd '/Applications/EServer/www/php-spc/source/libxslt' && make -j8 at phar:///Applications/EServer/www/php-spc/spc/src/globals/functions.php(100)
[08:14:20] [ERRO] #0 phar:///Applications/EServer/www/php-spc/spc/src/SPC/util/UnixShell.php(47): f_passthru('cd '/Applicatio...')
#1 phar:///Applications/EServer/www/php-spc/spc/src/SPC/builder/unix/library/libxslt.php(45): SPC\util\UnixShell->exec('cd '/Applicatio...')
#2 phar:///Applications/EServer/www/php-spc/spc/src/SPC/builder/LibraryBase.php(144): SPC\builder\macos\library\libxslt->build()
#3 phar:///Applications/EServer/www/php-spc/spc/src/SPC/builder/LibraryBase.php(152): SPC\builder\LibraryBase->tryBuild(true)
#4 phar:///Applications/EServer/www/php-spc/spc/src/SPC/builder/unix/UnixBuilderBase.php(143): SPC\builder\LibraryBase->tryBuild(false)
#5 phar:///Applications/EServer/www/php-spc/spc/src/SPC/command/BuildCliCommand.php(135): SPC\builder\unix\UnixBuilderBase->buildLibs(Array)
#6 phar:///Applications/EServer/www/php-spc/spc/src/SPC/command/BaseCommand.php(99): SPC\command\BuildCliCommand->handle()
#7 phar:///Applications/EServer/www/php-spc/spc/vendor/symfony/console/Command/Command.php(326): SPC\command\BaseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///Applications/EServer/www/php-spc/spc/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///Applications/EServer/www/php-spc/spc/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(SPC\command\BuildCliCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///Applications/EServer/www/php-spc/spc/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///Applications/EServer/www/php-spc/spc/bin/spc(20): Symfony\Component\Console\Application->run()
#12 /Applications/EServer/www/php-spc/spc(8): require('phar:///Applica...')

这个报错之前是先报错未安装cmake，然后通过brew安装cmake后报错就是如上了

**Comment by y1713375484** [comment]
编译的扩展有
./spc build --build-micro "apcu,bcmath,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,gd,iconv,intl,mbregex,mbstring,mysqli,mysqlnd,opcache,openssl,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,readline,redis,session,simplexml,sockets,sodium,sqlite3,tokenizer,xml,xmlreader,xmlwriter,xsl,zip,zlib" --debug

**Comment by y1713375484** [comment]
编译的过程有点长发不出来

**Comment by crazywhalecc** [comment]
你的错误信息刚好没有包含关键信息，编译错误应该在 `clang: error: linker command failed with exit code 1 (use -v to see invocation)` 上面的几句。

**Comment by y1713375484** [comment]
[1.txt](https://github.com/crazywhalecc/static-php-cli/files/14395910/1.txt)

**Comment by crazywhalecc** [comment]
删除 buildroot source 两个目录后再次构建试下？

**Comment by y1713375484** [comment]
依旧还是报错

**Comment by crazywhalecc** [comment]
还是同样的报错吗，如果是的话，发一下 `source/libxslt/config.log` 文件。

**Comment by y1713375484** [comment]
[Uploading config.log…]()

**Comment by y1713375484** [comment]
[config.log](https://github.com/crazywhalecc/static-php-cli/files/14396191/config.log)

**Comment by crazywhalecc** [comment]
1. 删除 ./buildroot/ ./source/ 两个目录
2. 运行 `./spc doctor 
3. 运行 `./spc doctor`
4. 运行 `./spc download --all --debug` 下载所有依赖
5. 运行 `./spc build xxxxx,yyyyyy --build-cli --debug` 并将错误日志完全拷贝出来

另外，我看你第一个发送的日志里面是用 `--from-zip` 来下载资源的，是从哪里下载的？

**Comment by crazywhalecc** [comment]
目前没看出来是什么问题，麻烦再把终端的信息发一下。

**Comment by y1713375484** [comment]
麻烦了
[终端报错.txt](https://github.com/crazywhalecc/static-php-cli/files/14396516/default.txt)

**Comment by y1713375484** [comment]
我卸载了cmake，然后通过doctor重新安装修复之后，并删除 ./buildroot/ ./source/ 目录重新编译还是报错
[终端报错.txt](https://github.com/crazywhalecc/static-php-cli/files/14396624/default.txt)
[config.log](https://github.com/crazywhalecc/static-php-cli/files/14396626/config.log)

**Comment by y1713375484** [comment]
<img width="449" alt="image" src="https://github.com/crazywhalecc/static-php-cli/assets/80376536/c441c470-31ea-4911-9c69-d5ac234867e8">
好像cmake还是x86的，我这是通过doctor安装的

**Comment by crazywhalecc** [comment]
那你的 Homebrew 是装在 `/usr/local/Homebrew` 的还是 `/opt/homebrew` 的？如果是前者，你可能需要安装一个 arm 的 homebrew。

**Comment by y1713375484** [comment]
是/usr/local/bin/brew

**Comment by y1713375484** [comment]
应该是解决了，现在提示在编译二进制文件是内存不足
yzh@yanzehangdeMacBook-Pro php-spc % ./spc micro:combine wbxt.phar
     _        _   _                 _           
 ___| |_ __ _| |_(_) ___      _ __ | |__  _ __  
/ __| __/ _` | __| |/ __|____| '_ \| '_ \| '_ \ 
\__ \ || (_| | |_| | (_|_____| |_) | | | | |_) |
|___/\__\__,_|\__|_|\___|    | .__/|_| |_| .__/   v2.1.0
                             |_|         |_|    

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 89772592 bytes) in phar:///Applications/EServer/www/php-spc/spc/src/SPC/command/MicroCombineCommand.php on line 89
yzh@yanzehangdeMacBook-Pro php-spc %

**Comment by y1713375484** [comment]
应该和我本地的PHP内存没关系吧

**Comment by crazywhalecc** [comment]
> 应该和我本地的PHP内存没关系吧

没关系，这个是一个小 Bug，如果使用 `micro:combine` 来结合代码和 micro 的话，默认的内存限制是 128M。我后面把默认的 memory_limit 调大一点就好了。如果文件过大，建议直接用 `cat` 命令：`cat buildroot/bin/micro.sfx wbxt.phar > my-app`

**Comment by y1713375484** [comment]
感谢大佬耐心解答，以捐赠，最后想问下，在MacBook上是不是不能打包linux、windows的可执行文件

**Comment by crazywhalecc** [comment]
> 感谢大佬耐心解答，以捐赠，最后想问下，在MacBook上是不是不能打包linux、windows的可执行文件

目前不能交叉编译，但你可以提前预编译好其他平台的 micro.sfx 然后在另外一个操作系统上组合你的代码。因为 PHP 代码可能会经常变化，但是 php 和相关扩展的变化确定后一般变化不多，可以提前定时使用 CI 编译好然后直接使用。
