### ISSUE TITLE
Segfault on `pg_connect` (`pgsql` extension)

### ISSUE THREAD

**Issue by kkovacs** [crazywhalecc/static-php-cli#353]
Apparently `static-php-cli` segfaults on the `pg_connect` call.

Steps to reproduce:

```
$ ./spc download --for-extensions=pgsql
$ ./spc doctor --auto-fix
$ ./spc build --build-cli pgsql
$ ./buildroot/bin/php index.php

Warning: pg_connect(): Unable to connect to PostgreSQL server: connection to server at "127.0.0.1", port 5432 failed: FATAL:  no PostgreSQL user name specified in startup packet
connection to server at "127.0.0.1", port 5432 failed: FATAL:  no PostgreSQL user name specified in startup packet in /persist/lara4/foo.php on line 2
Segmentation fault (core dumped)
```

Where `index.php` is:
```php
<?php
pg_connect("postgresql://root:xxxxx@127.0.0.1/postgres");
```

or alternatively (with same result):

```php
<?php
pg_connect("host=127.0.0.1 dbname=postgres user=root password=xxxxx");
```

Tested with Ubuntu 23.10 and Ubuntu 22.04, `x86_64` architecture.

The `no PostgreSQL user name specified in startup packet` is especially interesting, since there IS clearly a username specified in the connection string?

**Comment by crazywhalecc** [comment]
This issue seems related to: 

- https://github.com/beyondcode/herd-community/issues/254
- https://github.com/crazywhalecc/static-php-cli/issues/273
- https://github.com/Homebrew/homebrew-core/issues/155651

If this issue is still prevalent, I will review it again this week.

**Comment by kkovacs** [comment]
Dear @crazywhalecc,

you're entirely right -- this DOES seem related to SSL, since the bug doesn't happen with `sslmode=disable`:

```php
<?php
$conn = pg_connect("postgresql://root:xxxxx@127.0.0.1/postgres?sslmode=disable");
$result = pg_query($conn, "select version()");
var_dump(pg_fetch_all($result));
```

No segfault:

```bash
$ ./buildroot/bin/php foo.php
array(1) {
  [0]=>
  array(1) {
    ["version"]=>
    string(134) "PostgreSQL 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit"
  }
}
```

If you can update the library, that would be awesome.

P.s.: Thanks for all the great things you are doing for the PHP community! 🙇

**Comment by kkovacs** [comment]
Thank you for the quick action! I can confirm, building from `master` now it works with `sslmode=require` for me too.
