### ISSUE TITLE
咱么这个支持 zend 

### ISSUE THREAD

**Issue by TNT-ma** [crazywhalecc/static-php-cli#36]
我看swoole php -m 看到支持：
[Zend Modules]

暂这个没有能否添加 这个玩意好像是可以加载zend 插件

**Comment by crazywhalecc** [comment]
zend可能很难支持了，目前只支持标准的pecl扩展。

**Comment by TNT-ma** [comment]
> zend可能很难支持了，目前只支持标准的pecl扩展。

pecl 现在是支持了的吗？pecl似乎也行，如果用C++ 编写一个加密代码扩展，有源代码的情况下，是不是能将这个自定义扩展的文件编译内置在  sfx 里面

**Comment by dixyes** [comment]
https://github.com/dixyes/phpmicro/blob/master/patches/static_opcache_83.patch

但这个有点邪恶 只支持了opcache， 什么xdebug就甭想用了

**Comment by TNT-ma** [comment]
> https://github.com/dixyes/phpmicro/blob/master/patches/static_opcache_83.patch
> 
> 但这个有点邪恶 只支持了opcache， 什么xdebug就甭想用了
> 
> （你可以参考这个patch把你的zend扩展改一改编译进去，如果是别人的.so/dll就别想了，触发你够闲自己写ELF/PE loader
> 
> （但你都能在改PHP源码了，还纠结什么扩展，加密直接做到PHP解释器里不好吗

你发的这个是啥意思？ 我还没看懂
