### ISSUE TITLE
[FEATURE] support for uuid extensions :pray: 

### ISSUE THREAD

**Issue by jderusse** [crazywhalecc/static-php-cli#362]
Using uuid is pretty common in applications.

existing polyfills and vendors provide alternatives, but using the extension https://pecl.php.net/package/uuid provides better performance.

**Comment by crazywhalecc** [comment]
Added, need integration test 👍 #363

**Comment by jderusse** [comment]
wooowww that was fast 😍

**Comment by crazywhalecc** [comment]
Yeah everything is ready to add and I happen to be writing some static-php related documentation.
