### ISSUE TITLE
Feature Request -- add AMQP extension

### ISSUE THREAD

**Issue by dgoosens** [crazywhalecc/static-php-cli#365]
Hi,

I wonder if it would be possible to add the AMQP extension to the supported extensions?  
TBH, I would need to get this working in a standalone build of @dunglas's #FankenPHP yet I figure I'm not the only one that would need support for RabbitMQ...

Thanks a lot in advance,  
Dmitri

**Comment by crazywhalecc** [comment]
Added, need integration test 👍 #366
