### ISSUE TITLE
Failed to build php 7.4 with lib xml

### ISSUE THREAD

**Issue by lucashtc** [crazywhalecc/static-php-cli#370]
When building the build I receive an xml lib missing error.
When checking, I noticed that the file I was looking for was in the lib64 folder(buildroot/lib64/pkgconfig/libxml-2.0.pc) and not in lib.
After copying the file to the correct folder(buildroot/lib/pkgconfig/), the build follows the build correctly 

The same happens when building libxslt.
cp buildroot/lib64/libxml2.a buildroot/lib/

Error message:
[13:13:22] [WARN] PHP Warning: file_get_contents(/home/lucasht/projects/php_static/buildroot/lib/pkgconfig/libxml-2.0.pc): Failed to open stream: No such file or directory in phar:///home/lucasht/projects/php_static/spc/src/SPC/store/FileSystem.php on 48

**Comment by crazywhalecc** [comment]
What distribution (including architecture) are you compiling on? Use `spc` binary?

If you're using the latest spc, there shouldn't be a problem. If you have already built before, it is recommended to delete the `buildroot` and `source` directories and try again.

**Comment by lucashtc** [comment]
I deleted all the folders and am using the latest spc.

tatic-php-cli 2.1.3 
CentOS Stream 9
x86_64

**Comment by crazywhalecc** [comment]
Oh, I haven't tested on CentOS Stream yet, it may caused by CentOS build tools. I will try on CentOS.

You can build in Docker if you have installed.

**Comment by crazywhalecc** [comment]
I figured it out. Only RHEL and CentOS will produce `lib64` dir and the default `--libdir` option for RHEL is `lib64`. I will fix it later, thank you for your reporting!

**Comment by lucashtc** [comment]
It was nothing.
I successfully utilized Docker.
