### ISSUE TITLE
大佬： 单独编译一个依赖库 命令是啥？

### ISSUE THREAD

**Issue by jingjingxyk** [crazywhalecc/static-php-cli#39]
比如我要编译 libjpeg 
配置比照着 libpng 都加好了，如何单独编译一个  libjpeg 库 

```
./bin/spc build gd --cc=clang --cxx=clang++ --debug 

```

为啥 把依赖库 合并放到 buildroot 目录下bin 、lib 、include ，而不是每个库独占一个目录

![image](https://user-images.githubusercontent.com/6836228/233766760-07ac8d7f-b7ab-45a0-ad26-365f665305d2.png)

有啥考量吗？

**Comment by crazywhalecc** [comment]
编译单独的 lib 可以使用命令 `bin/spc build:libs libpng --debug`。

另外，不独占目录的原因主要是有库相互之间有依赖的时候处理起来比较简单，分开的话需要单独维护多个 PREFIX，增加了复杂度。而一般情况下，依赖的库编译后也往往只会有一个或几个 .a 文件和 .h 头文件，配置文件内已对相关文件描述了。

**Comment by jingjingxyk** [comment]
@crazywhalecc  依赖库验证完毕。其中有个问题，想不通， 为啥要这样设置   https://github.com/crazywhalecc/static-php-cli/pull/41/files#diff-a64f30f4c4f248dfe15e99763ad521214bed3d530a2cd41f993931aeceef5dd9 

```php
define('SEPARATED_PATH', [
    '/' . pathinfo(BUILD_LIB_PATH)['basename'], // lib
    '/' . pathinfo(BUILD_INCLUDE_PATH)['basename'], // include
    BUILD_ROOT_PATH,
]);
```

**Comment by crazywhalecc** [comment]
@jingjingxyk 这个是我最先开始为了让这些库的依赖路径走系统的根目录，同时为了方便代码中可以使用双引号直接插入变量的形式弄的，是两个方面的原因。

第一个说让依赖走系统的根目录主要是为了能让某些库（例如 openssl 等）可以读取系统的证书、配置、依赖库和依赖的头文件等，和 `make install DESTDIR=xxx` 配合使用，这样构建出来的库也可以避免带上编译时系统环境的 prefix 等信息。

第二个自己手写 `/lib`、`/include` 也是可以的，最主要还是围绕 BUILD_ROOT_PATH 这个进行。如果在新增库的时候不想用，也可以直接写，但最好在 `make install` 的时候使用 `DESTDIR=BUILD_ROOT_PATH` 参数。

**Comment by jingjingxyk** [comment]
> 

明白了
