### ISSUE TITLE
大佬，拉取你新的代码 然后再github actions构建 又报错了，有时间您看一下吧

### ISSUE THREAD

**Issue by tanhongbin-php** [crazywhalecc/static-php-cli#397]
不管啥扩展都是报错这个，应该不是扩展的问题
Error relocating /usr/lib/libcurl.so.4: SSL_get0_group_name: symbol not found
[09:25:33] [ERRO] failed http fetch
Error: Process completed with exit code 1

**Comment by crazywhalecc** [comment]
看起来是在 `download` 阶段产生的错误，这个可能是系统上装的 curl 库缺少 openssl 库导致的，建议先试试 `curl --help` 命令能否正常使用。该问题应该和 static-php-cli 无关。
