### ISSUE TITLE
bug: Linux x86_64 build failed

### ISSUE THREAD

**Issue by crazywhalecc** [crazywhalecc/static-php-cli#416]
https://github.com/crazywhalecc/static-php-cli/actions/runs/8795280372/job/24136081565

**Comment by simonhamp** [comment]
Looks like you're trying to run `f_passthru()` in both [`src/SPC/util/WindowsCmd.php`](https://github.com/crazywhalecc/static-php-cli/blob/main/src/SPC/util/WindowsCmd.php#L49) and [`src/SPC/util/UnixShell.php`](https://github.com/crazywhalecc/static-php-cli/blob/main/src/SPC/util/UnixShell.php#L47)

But I don't think that function exists; isn't it [`fpassthru`](https://www.php.net/manual/en/function.fpassthru.php)?

**Comment by simonhamp** [comment]
Ah no, I see you've got a [custom `f_passthru` function](https://github.com/crazywhalecc/static-php-cli/blob/main/src/globals/functions.php#L84-L103)

**Comment by crazywhalecc** [comment]
@simonhamp Maybe it's caused by imagemagick dependencies (openmp). And yeah we have some wrapper functions for debugging and logging.

**Comment by simonhamp** [comment]
I was bumping into it when trying to do a Windows build, but it turned out that I needed to run the `doctor` first

I haven't checked Linux builds directly, it just happened to look similar

**Comment by simonhamp** [comment]
I guess if nothing has changed in SPC, it may be that GitHub have changed the configuration of the hosted action runner images?

**Comment by crazywhalecc** [comment]
> https://github.com/crazywhalecc/static-php-cli/actions/runs/8795280372/job/24136081565

By default I did not modify any compilation parameter changes, the only change was that I introduced environment variables. But the error message shows a problem with openmp. I encountered this problem a long time ago.
