### ISSUE TITLE
Compiled Windows executable isn't running

### ISSUE THREAD

**Issue by simonhamp** [crazywhalecc/static-php-cli#418]
I've been able to compile PHP8.2 on a Windows GitHub Action 🎉

However, when I then try to use it on a Windows machine, I get the following error:
![image](https://github.com/crazywhalecc/static-php-cli/assets/31628/e4d52d2f-568d-4d75-befb-3b39b28d097b)

Seems that some part (I'm guessing curl?) is depending on `nghttp2` but this isn't statically link.

My extension string was:
```
bcmath,ctype,zlib,openssl,curl,iconv,xml,dom,fileinfo,filter,mbstring,pdo,sqlite3,pdo_sqlite,session,simplexml,sockets,tokenizer
```

**Comment by crazywhalecc** [comment]
Fixed in main branch.
