### ISSUE TITLE
postgresql: Failed to get pkg-config information

### ISSUE THREAD

**Issue by dunglas** [crazywhalecc/static-php-cli#430]
The FrankenPHP CI is red since yesterday because of a linking issue:

https://github.com/dunglas/frankenphp/actions/runs/8866392111/job/24343786038

```
#27 731.9 [08:59:17] [ERRO] Uncaught SPC\exception\RuntimeException: Failed to get pkg-config information! at /go/src/app/dist/static-php-cli/src/SPC/builder/unix/library/postgresql.php(64)
#27 731.9 [08:59:17] [ERRO] #0 /go/src/app/dist/static-php-cli/src/SPC/builder/LibraryBase.php(144): SPC\builder\linux\library\postgresql->build()
```

**Comment by crazywhalecc** [comment]
Seems caused by #431 . Temporary solution is downloading old version of ncurses (6.4).

The possible reason may be that the 'ncurses. pc' file was not correctly output after compiling version 6.5.

**Comment by dunglas** [comment]
Thank you, enjoy your vacation!
