### ISSUE TITLE
固定编译器选项比较合适，否则选项越多，需要写兼容选项就越多

### ISSUE THREAD

**Issue by jingjingxyk** [crazywhalecc/static-php-cli#44]
linux x86_64 debian  环境下
```bash
# 1
./bin/spc build gd,zlib  --cc=gcc       --cxx=g++ --build-cli  --debug
# 2
./bin/spc build gd,zlib  --cc=musl-gcc  --cxx=g++ --build-cli --debug
# 3 
./bin/spc build gd,zlib  --cc=clang     --cxx=clang++ --build-cli --debug
```

每个都 需要解决不同的编译问题！

比如第2种：
![image](https://user-images.githubusercontent.com/6836228/234076692-b9d83834-9f7d-486d-930d-ded9fc045932.png)

**Comment by crazywhalecc** [comment]
目前来说就是固定的，Linux 统一使用 musl-gcc，macOS 使用 clang。但有个特殊的地方在于，alpine linux 下 gcc 就是 musl-gcc，没有 musl-gcc 这个命令，所以需要特殊指定一下命令。但这并不需要特殊考虑和兼容多个编译器，只是命令名称上的差别。
