### ISSUE TITLE
Add the parallel extension

### ISSUE THREAD

**Issue by dunglas** [crazywhalecc/static-php-cli#443]
[`ext-parallel`](https://github.com/krakjoe/parallel) is very convenient with FrankenPHP and in CLI.
It requires a ZTS build, but as ZTS is supported by Static PHP CLI, this isn't an issue.

If you're ok for adding it, I can work on a patch.

**Comment by simonhamp** [comment]
Intrigued by this one!

**Comment by crazywhalecc** [comment]
Seems easy to support it on macOS and Linux. I just add the config part and it's working on my mac.

I'm always open to this, and it would be better if you could add additional tests for it.

**Comment by crazywhalecc** [comment]
Added. Track the latest information here: #444
