### ISSUE TITLE
Technical details & code preservation

### ISSUE THREAD

**Issue by kiler129** [crazywhalecc/static-php-cli#461]
This may be a very trivial question, but I wasn't able to find answer to in the documentation: **what the resulting binary contains in terms of compiled code?** 

### Rationale
While guarding code isn't my primary worry, attempting to distribute some pre-compiled tools while not having source code immediately readable would be a plus. While it's true any code is open-source if you can fire up Ghidra, making it a bit harder is usually beneficial. In addition, antiviruses like to mark binaries with scripts inside as a threat ;)

### Performance
I wonder if it would be feasible for SPC to embed resulting opcode and execute that instead of raw PHP source. That way it could kill two birds with one stone: the code would be somewhat obfuscated, while also making the binary startup quicker.

**Comment by crazywhalecc** [comment]
This has always been a difficult problem to solve. To run the opcode directly, at least a lot of patches are needed:

1. Re-apply https://wiki.php.net/rfc/direct-execution-opcode 
2. Modify some opcode instructions to be system-independent
3. After compiling micro.sfx, use spc to compile the same version of opcode

All three steps currently require a huge amount of work on php-src, which may not be something I can do at the moment.

If you don't want to directly concatenate the PHP source code in plain text, you can use GZ or BZ2 to compress Phar or use `php-cli` with encrypt extensions. In short it is currently difficult to provide an other effective solution based on the official PHP code.
