### ISSUE TITLE
Build micro error when using require 

### ISSUE THREAD

**Issue by joelwurtz** [crazywhalecc/static-php-cli#476]
Not sure what changed, but since a few days when we try to build micro and adding a phar to it does not work anymore, we go those kind of errors:

```
...

Warning: require(): Seek on self stream failed in phar:///home/joelwurtz/Workspace/Oss/castor/castor.linux-amd64/vendor/composer/autoload_real.php on line 42

Warning: include(): Seek on self stream failed in phar:///home/joelwurtz/Workspace/Oss/castor/castor.linux-amd64/vendor/composer/ClassLoader.php on line 576

Warning: include(): Seek on self stream failed in phar:///home/joelwurtz/Workspace/Oss/castor/castor.linux-amd64/vendor/composer/ClassLoader.php on line 576

Warning: include(): Seek on self stream failed in phar:///home/joelwurtz/Workspace/Oss/castor/castor.linux-amd64/vendor/composer/ClassLoader.php on line 576

Fatal error: Uncaught ErrorException: Warning: include(): Seek on self stream failed in phar:///home/joelwurtz/Workspace/Oss/castor/castor.linux-amd64/vendor/composer/ClassLoader.php:576
Stack trace:
#0 phar:///home/joelwurtz/Workspace/Oss/castor/castor.linux-amd64/vendor/composer/ClassLoader.php(576): include()
#1 phar:///home/joelwurtz/Workspace/Oss/castor/castor.linux-amd64/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('phar:///home/jo...')
#2 phar:///home/joelwurtz/Workspace/Oss/castor/castor.linux-amd64/vendor/symfony/error-handler/ErrorHandler.php(498): Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#3 [internal function]: Symfony\Component\ErrorHandler\ErrorHandler->handleException(Object(ErrorException))
#4 {main}
  thrown in phar:///home/joelwurtz/Workspace/Oss/castor/castor.linux-amd64/vendor/composer/ClassLoader.php on line 576
  ```
  
I try using different versions of SPC, use specific version of PHP and even checkout specific version of `phpmicro` but we keep having this failure, not sure where it fails here. 

Do you have some inputs on how to debug this so we can fix this error ?

**Comment by crazywhalecc** [comment]
If the problem only occurs with a recent build, it may be related to a major version upgrade of phpmicro. Could you provide a minimal reproducible phar or a process for building a phar?

**Comment by joelwurtz** [comment]
With phar on this release : https://github.com/jolicode/castor/releases/tag/v0.17.1 i get the error

We execute this commands : 

```
spc 'download' '--for-extensions=mbstring,phar,posix,tokenizer,pcntl,curl,filter,openssl' '--with-php=8.3'
```

```
spc 'build' 'mbstring,phar,posix,tokenizer,pcntl,curl,filter,openssl' '--build-micro' '--with-micro-fake-cli' '--arch=x86_64'
```

```
spc 'micro:combine' 'castor.linux-amd64.phar' '--output=castor.linux-amd64'
```

**Comment by crazywhalecc** [comment]
I just asked the author of phpmicro and debugged with him and found out that it should be a bug in phpmicro itself. We will fix it tomorrow.

**Comment by crazywhalecc** [comment]
phpmicro has fixed phar issue, remember cleaning `buildroot` and `source`, and `bin/spc del-download micro && bin/spc download micro` to download the latest micro repo to build.

**Comment by joelwurtz** [comment]
Thanks a lot <3, and also thanks to the author of phpmicro for its quick reaction.

It seems to be working with last SPC version, however older versions still have the bug, (i think this fork https://github.com/static-php/phpmicro should be updated in order to make it work on older versions)

**Comment by crazywhalecc** [comment]
I've updated static-php fork repo 👏

**Comment by HallexCosta** [comment]
@crazywhalecc  This new phpmicro update resolved the initial error, but now I'm getting a new error.
I followed the instructions to remove the `buildroot` and `source` folders `bin/spc del-download micro && bin/spc download micro`


However, when I try to run the binary with `./my-binary` it shows the hyperf commands normally.![image](https://github.com/crazywhalecc/static-php-cli/assets/55293671/61df02b9-754c-4eee-abd7-771e6b133161)


Now if I try to run the server with the command `./my-binary start`, it shows error logs
![image](https://github.com/crazywhalecc/static-php-cli/assets/55293671/0bcaeeeb-c8ae-4e9c-a359-dde19e996d6c)
