### ISSUE TITLE
Add php-spx extension

### ISSUE THREAD

**Issue by LordSimal** [crazywhalecc/static-php-cli#496]
https://github.com/NoiseByNorthwest/php-spx is our preferred way of doing local profiling.

It would be awesome if this - also awesome - package would add support for that extension 😁

**Comment by crazywhalecc** [comment]
I tried to add spx, and it cannot be directly added in php-src embed building. There are too many imcompatible code and config in `php-spx` itself. 

I'll check later in my spare time, it's do need to fix php-spx source first.

**Comment by LordSimal** [comment]
It was worth a try, thanks for checking.
