### ISSUE TITLE
Unable to download xz

### ISSUE THREAD

**Issue by nicholasdille** [crazywhalecc/static-php-cli#497]
With the latest version 2.2.4, `spc` is unable to download [`xz` version 5.4.6 from `fossies.org`](https://fossies.org/linux/misc/xz-5.4.6.tar.xz).

This was fixed in crazywhalecc/static-php-cli#495 by upgrading to `xz` 5.4.7 but `spc` remains broken.

Any advice how to solve this with `spc` version 2.2.4 while waiting for a release?

**Comment by crazywhalecc** [comment]
When downloading, you can override download url using `-U {source_name}:{url}` option. For example: `bin/spc download --for-extensions=XXX,YYY -U "xz:https://github.com/tukaani-project/xz/releases/download/v5.6.2/xz-5.6.2.tar.gz"`.

And btw, the current spc version is not very meaningful. Generally, the patch version number is updated once a week, or the minor version num add with a big feature added. And if you do not need to use the SPC API and only use the command line, the main branch is more usable.

**Comment by nicholasdille** [comment]
Thanks!
