### ISSUE TITLE
How to add ioncube extension

### ISSUE THREAD

**Issue by louishot** [crazywhalecc/static-php-cli#507]
I'd like to use ioncube Protecting source code

**Comment by crazywhalecc** [comment]
ioncube is a closed source project, so we cannot compile it.

- Linux static binary does not support `.so` file, it's not supported.
- macOS and windows static php binary can use `.so,.dll` file with external `php.ini`, you can download and add external extension to your static php.

**Comment by louishot** [comment]
> ioncube is a closed source project, so we cannot compile it.
> 
> * Linux static binary does not support `.so` file, it's not supported.
> * macOS and windows static php binary can use `.so,.dll` file with external `php.ini`, you can download and add external extension to your static php.

All right so Linux static binary cannot to load .so file as extension?

**Comment by crazywhalecc** [comment]
> All right so Linux static binary cannot to load .so file as extension?

@louishot No. See: https://static-php.dev/en/faq/#can-statically-compiled-php-install-extensions
