### ISSUE TITLE
windows 版本spc-max 可以redis也默认吗

### ISSUE THREAD

**Issue by ooing** [crazywhalecc/static-php-cli#509]
redis目前算比较常用扩展

**Comment by crazywhalecc** [comment]
目前还没有完成 Windows 下的 redis 扩展支持，如需支持，建议修改此 Issue 或新开一个相关的，我将在我个人的任务列表中追踪问题。

另外有关 spc-max 的支持，后续如果评估 redis 扩展不会和其他扩展产生冲突，将会在 redis 支持后加入。
