### ISSUE TITLE
iconv fails with CP437 charset

### ISSUE THREAD

**Issue by mpociot** [crazywhalecc/static-php-cli#513]
This error popped up with Laravel Herd and can be reproduced like this:

```
echo iconv('UTF-8', 'CP437', 'foo');
```

This results in: Warning: iconv(): Wrong encoding, conversion from "UTF-8" to "CP437" is not allowed in php shell code on line 1

**Comment by crazywhalecc** [comment]
It's caused by libiconv build configure (missing `--enable-extra-encodings`). It will be added later.
