### ISSUE TITLE
现在无法构建8.0 了吗？docker 怎么构建都是8.2 

### ISSUE THREAD

**Issue by TNT-ma** [crazywhalecc/static-php-cli#514]
8.0版本 没了吗？

**Comment by crazywhalecc** [comment]
PHP 版本由下载的版本确定，8.0 是支持的，可能是因为没有正确切换 PHP 版本。可以使用 `bin/spc-alpine-docker switch-php-version 8.0` 来切换到 8.0 版本；或者删除 `buildroot` 和 `source` 目录并输入命令 `bin/spc-alpine-docker del-download php-src && bin/spc-alpine-docker download php-src --with-php=8.0`（两者其实是完全相同的方式）。
