### ISSUE TITLE
Windows下的redis扩展支持

### ISSUE THREAD

**Issue by ywisax** [crazywhalecc/static-php-cli#518]
Redis扩展属于很常用的扩展，如果在Windows下也能支持，那 static-php-cli 的实用性会进一步提高。

**Comment by crazywhalecc** [comment]
已添加。

**Comment by ywisax** [comment]
https://dl.static-php.dev/static-php-cli/windows/spc-max/ 这里的包能更新一下吗？方便测试

**Comment by crazywhalecc** [comment]
@ywisax 已添加
