### ISSUE TITLE
需要Oracle扩展SqlServer的扩展

### ISSUE THREAD

**Issue by abinxx** [crazywhalecc/static-php-cli#52]
需要Oracle扩展SqlServer的扩展

**Comment by crazywhalecc** [comment]
支持 Oracle 和 SQL Server 可能是比较困难的，因为 oci8 和 sqlsrv 扩展需要链接 Oracle 和 mssql 的闭源库，闭源库只提供了动态链接的 `.so` 文件，而本项目的静态编译需要静态的链接库 `.a`，如果官方没有提供 `.a` 且上游依赖 Instant Client 和 odbc driver 保持闭源无法自行编译的话，暂时是没有办法解决的。

当然还有一计就是让 static-php-cli 编译的 php-cli 不是纯静态，让他支持 ffi 动态链接其他库的特性来曲线救国实现加入 oci8、sqlsrv 扩展，但那样不符合本项目的初衷。
