### ISSUE TITLE
Support PHPRedis 6.0

### ISSUE THREAD

**Issue by mpociot** [crazywhalecc/static-php-cli#538]
Is there a technical reason why the PHPRedis extension is not being used in the latest version, which is 6.x?

https://github.com/phpredis/phpredis

**Comment by crazywhalecc** [comment]
Currently it is fixed version 5.3.7, and the latest version theoretically should not have compilation problems.

I've tested building 6.0.2 on my Linux server, and the only things need to do is supporting `COPYING` moved to  `LICENSE` problem.
