### ISSUE TITLE
Sqlsrv extension regression

### ISSUE THREAD

**Issue by mpociot** [crazywhalecc/static-php-cli#541]
I noticed that there is a regression bug that happens as soon as I add `sqlsrv` to the extension list.

My build command:

```
export SPC_CMD_VAR_PHP_MAKE_EXTRA_CFLAGS="-g -Os" && ./bin/spc build intl,pdo_sqlite,sqlite3,curl,openssl,tokenizer,bcmath,bz2,calendar,dba,ftp,iconv,mysqli,mbstring,mbregex,xml,simplexml,ctype,dom,pdo,filter,session,zlib,fileinfo,pdo_mysql,posix,sockets,shmop,sodium,sysvmsg,sysvsem,sysvshm,gd,zip,gmp,redis,xmlwriter,phar,exif,xmlreader,readline,pcntl,soap,imagick,ffi,password-argon2,pgsql,pdo_pgsql,imap,ldap,xsl,igbinary,zstd,opcache,mongodb --debug --build-cli  --build-fpm --with-libs=nghttp2,liblz4  --debug --no-strip
```

When running the following code with this PHP binary, you get the correct result `0`:

```
echo str_word_count('мама', 0, null);
```

When you add `sqlsrv` and compile a PHP binary, this code breaks and returns `4` instead.

**Comment by crazywhalecc** [comment]
This bug seems to exist on Homebrew's PHP as well, so perhaps track this issue upstream would be better.

**Comment by mpociot** [comment]
Thank you for tracking this issue down! I'll create an issue on the upstream repository 👍
