### ISSUE TITLE
PHP 8.4 support

### ISSUE THREAD

**Issue by mpociot** [crazywhalecc/static-php-cli#547]
PHP 8.4 is now in the release candidate phase, with the official release scheduled for November 21.
It would be great if we get PHP 8.4 support in static-php

**Comment by mpociot** [comment]
The PHPMicro patches needed for this to begin with can be found in my fork
https://github.com/dixyes/phpmicro/compare/master...mpociot:phpmicro:php-84-fixes

Sodium also seems to cause an issue, as the `sodium.php` file currently tries to remove all lines that contain `-Wno-logical-op`

Since PHP 8.4, this is no longer a single line though, which produces errors as the `-Werror` line remains in the config.m4 file after patching:

https://github.com/php/php-src/blob/master/ext/sodium/config.m4#L21-L22

**Comment by crazywhalecc** [comment]
Seems https://github.com/dixyes/phpmicro/pull/3 iconv part is duplicated.

Also, I haven't tested these patches yet, but if they work on Herd, we can use them first.

**Comment by mpociot** [comment]
Yeah that PR is already outdated as it was based on an early alpha release. 
I managed to compile 8.4.0RC1 for Herd. I had to disable some extensions that would need further investigation (like duplicate symbols with argon2 and sodium)

**Comment by crazywhalecc** [comment]
If there are extension-independent phpmicro patches that need to be updated, we could use them and test them in advance. 

For extensions, continue testing in the draft PR supporting 8.4 (will do) until most extensions are available.

**Comment by ikilobyte** [comment]
@crazywhalecc PHP 8.4 already released

**Comment by crazywhalecc** [comment]
@ikilobyte Yeah, but this week I have no time to do with static-php project, some final tests needs to be done.
