### ISSUE TITLE
Linking issue with PHP 8.4 and libpq

### ISSUE THREAD

**Issue by dunglas** [crazywhalecc/static-php-cli#560]
Building the static embed SAPI with Postgres causes a linking issue: the Postgres library isn't found: https://github.com/dunglas/frankenphp/actions/runs/11986745297/job/33420123250?pr=1193#step:6:21679

The problem only occurs with PHP 8.4.

**Comment by dunglas** [comment]
Passing explicitly something `${PWD}/buildroot/lib/libpgcommon.a ${PWD}/buildroot/lib/libpgport.a ${PWD}/buildroot/lib/libpq.a` to the linker works as a workaround.

**Comment by crazywhalecc** [comment]
PHP 8.4 has changed pgsql config.m4: https://github.com/php/php-src/commit/f4ce50ddfbb71cdf5241d2c92454d8b053ca5008#diff-41d568c7fe3330be65b29eea92eba5dfca3a928100fadd3e7a382140786a9eceL92

**Comment by dunglas** [comment]
The problem seems to still be there: https://github.com/dunglas/frankenphp/actions/runs/12233575592/job/34120969565?pr=1231

**Comment by crazywhalecc** [comment]
@dunglas It seems to be caused by a corrupted pg_config. Simply not specifying the directory will bypass pg_config and fix the missing libraries. See #572

**Comment by dunglas** [comment]
Thank you!

**Comment by dunglas** [comment]
It looks like the issue persists 😅 https://github.com/dunglas/frankenphp/actions/runs/12237202736/job/34132460168?pr=1231

**Comment by dunglas** [comment]
Event after #567, the problem persists: https://github.com/dunglas/frankenphp/actions/runs/12325289480/job/34404346372?pr=1231

**Comment by crazywhalecc** [comment]
@dunglas I'm not sure which extension causes this bug, but it's working and no problem with `spc-config`. Using `php-config` also needs patching or passing `prefix` and other additional flags.

**Comment by dunglas** [comment]
Sorry I probably missed something but what is `spc-config`? Should we update our build script to use it?

**Comment by crazywhalecc** [comment]
@dunglas #573 I added `spc-config` for static-php:

```bash
# Before
buildroot/bin/php-config --libs

# Now
bin/spc spc-config $EXTENSIONS --with-libs=$LIBS --libs
```

There are also sanity checks using `spc-config` after building embed SAPI. See: https://static-php.dev/en/guide/manual-build.html#embed-usage
