### ISSUE TITLE
php-config --version returns an empty string

### ISSUE THREAD

**Issue by dunglas** [crazywhalecc/static-php-cli#563]
Since recently, the `php-config --version` utility returns an empty string. It used to return the "human readable" PHP version.
The `php-config --vernum` flag works properly.

This affects PHP 8.3 as well as PHP 8.4. This doesn't look like an upstream bug because `php-config --version` works as expected in the official Docker image.

See also https://github.com/dunglas/frankenphp/issues/1199

**Comment by dunglas** [comment]
Ok, this comes from  the `config.status` file, which contains an empty `PHP_VERSION` variable with SPC (but not for other builds):

```
S["PHP_VERSION"]=""
```

**Comment by crazywhalecc** [comment]
Seems some extension makes php version disappear. I tried to compile only several extensions and it's good.

For fastest tests, we may need to make an matrix, or only run `configure` and stop compiling for debugging.

**Comment by crazywhalecc** [comment]
This may be due to the config.m4 of the parallel extension: 

- https://github.com/crazywhalecc/static-php-cli/actions/runs/12176414345?pr=569
- https://github.com/krakjoe/parallel/blob/853798dffbbd78e394588c271ec7df9997e0476a/config.m4#L17
