### ISSUE TITLE
php embed sapi：undefinded reference to 'sigsetjmp'

### ISSUE THREAD

**Issue by KingBes** [crazywhalecc/static-php-cli#564]
System：Ubuntu 、deepin

bulid
```sh
./spc build --build-all "apcu,bcmath,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,gd,iconv,intl,mbregex,mbstring,mysqli,mysqlnd,opcache,openssl,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,readline,redis,session,simplexml,sockets,sodium,sqlite3,tokenizer,xml,xmlreader,xmlwriter,xsl,zip,zlib" --with-upx-pack --debug

```

cphp.c

```c
#include <sapi/embed/php_embed.h>

int main(int argc,char **argv){

    PHP_EMBED_START_BLOCK(argc,argv)

    zend_file_handle file_handle;

    zend_stream_init_filename(&file_handle,"index.php");

    if(php_execute_script(&file_handle) == FAILURE){
        php_printf("Failed to execute PHP script.\n");
    }

    PHP_EMBED_END_BLOCK()
    return 0;
}
```

index.php
```php
<?php

echo "hello world" . PHP_EOL;
```

build.sh

```sh
gcc \
$(./buildroot/bin/php-config --includes) \
-L$(./buildroot/bin/php-config --prefix)/lib \
cphp.c \
-lphp \
$(./buildroot/bin/php-config --libs) \
-lm -lresolv -ldl -lpthread -lc \
-Wl,-rpath=$(./buildroot/bin/php-config --prefix)/lib
```

![89058C07043238F6B5F5294787F6477A](https://github.com/user-attachments/assets/6d4ab8ea-6b4f-42ba-a684-d30e1069cadb)

**Comment by KingBes** [comment]
![b7e12366-97d5-4e2b-b019-411690340fff](https://github.com/user-attachments/assets/5168d714-9883-472a-813b-11d52721401b)

**Comment by dunglas** [comment]
Can you try if `--with-upx-pack` fixes the issue? I'm not sure this flag is really compatible with building a static library.

**Comment by KingBes** [comment]
> Can you try if `--with-upx-pack` fixes the issue? I'm not sure this flag is really compatible with building a static library.

Thanks for the reminder, but the flag `--with-upx-pack` does not affect the result.

**Comment by dunglas** [comment]
That's weird. FrankenPHP is using the embed SAPI and doesn't have this issue.
Would you be able to provide us a minimal reproducer?

**Comment by crazywhalecc** [comment]
@KingBes I tested and it's working, but indeed there are some bugs need to be fixed.

I'm using FrankenPHP's default extension combination to build embed SAPI, and changed `buildroot/bin/php-config` file, set `prefix=""` to `prefix="/path/to/buildroot"`. My working command:

```bash
# spc build command
bin/spc build apcu,bcmath,bz2,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,ftp,gd,gmp,gettext,iconv,igbinary,imagick,intl,ldap,mbregex,mbstring,mysqli,mysqlnd,opcache,openssl,parallel,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,protobuf,readline,redis,session,shmop,simplexml,soap,sockets,sodium,sqlite3,ssh2,sysvmsg,sysvsem,sysvshm,tidy,tokenizer,xlswriter,xml,xmlreader,xmlwriter,zip,zlib,yaml,zstd --build-cli --build-micro --debug --enable-zts --build-embed

# edit php-config file using sed or vim or something.....

# compile, use musl-gcc (glibc gcc cannot be compiled statically)
/usr/local/musl/bin/x86_64-linux-musl-cc $(buildroot/bin/php-config --includes) -L$(pwd)/buildroot/lib a.c -lphp $(buildroot/bin/php-config --libs) -lm -lresolv -ldl -lpthread -lc -Wl,-rpath=$(pwd)/buildroot/lib -lpq -lpgport -lpgcommon -lgomp -lstdc++ -static
```

**Comment by crazywhalecc** [comment]
I found some bugs:

- #560 (strange bug but I do use the same way to make it work: Passing `-lpq -lpgcommon -lpgport`)
- #563
- Missing prefix (may be defined in `./configure` argument or inserting a patch function in `php-config`?)
- Missing build flags in php-config (Maybe adding -lresolv -lstdc++ these flags to php-config would be better?)
- Missing compiler guide (Most developers are using glibc-gcc incorrectly?)

I'm not sure about the habits of most developers who use embed, so it would be great if you or someone could provide some suggestions.
