### ISSUE TITLE
how to add custom extension?

### ISSUE THREAD

**Issue by shellphy** [crazywhalecc/static-php-cli#565]
I wrote a simple extension using zephir, can I add it myself?

**Comment by crazywhalecc** [comment]
You can add your own extension. In general, you need to do

1. If your extension is public, add download link in `config/source.json`.
2. Add your extension info in `config/ext.json`.
3. Add dependencies in `config/lib.json`, `src/SPC/builder/xxx/library/yyy.php` if you are using other libraries.
4. Add `src/SPC/extension/zzz.php` and add some configure args, sanity checks and patches.

For example, in the simplest case, your extension does not depend on any other libraries when using `phpize && ./configure && make && make install` normally, and there is only `--enable-XXX` option in `config.m4`, you can directly add your extension in `config/ext.json`, copy your extension to `source/php-src/ext/XXX` and compile.

Of course, there are many details I haven't mentioned, but in general, as long as you can prove that your extension can be dynamically compiled, static compilation is usually just as easy.
