### ISSUE TITLE
linux 没法自动拉取依赖吗？

### ISSUE THREAD

**Issue by TNT-ma** [crazywhalecc/static-php-cli#57]
./bin/spc doctor
一直提示我：musl-libc is not installed on your systemSome check items can not be fixed !
但是我musl-libc 是安装了的

使用：./bin/spc fetch --all  
[20:11:34] [INFO] Fetching source php-src [1/42] 
一直卡着不动  半小时没动静

**Comment by crazywhalecc** [comment]
> 一直提示我：musl-libc is not installed on your systemSome check items can not be fixed !

Linux 现在我还没完全适配 doctor，过段时间加一下。

> 一直卡着不动 半小时没动静

人在中国大陆地区的话，建议先搭梯子下载。如果你访问 GitHub 速度够快的话，我刚才为本项目的 GH Action 添加了一个 downloads 目录上传的动作，你可以使用本项目 Action 构建的最新的 `download-files`，解压并存放到本地的项目根目录即可。

**Comment by TNT-ma** [comment]
香港服务器

**Comment by crazywhalecc** [comment]
下载时候可以加上 `--debug` 参数，显示进度。

**Comment by crazywhalecc** [comment]
> > 下载时候可以加上 `--debug` 参数，显示进度。
> 
> 今天试了一下构建命令： ./bin/spc build "bcmath,openssl,tokenizer,sqlite3,pdo_sqlite,ftp,curl" --build-cli --build-micro
> 
> [21:03:14] [CRIT] Build failed with SPC\exception\RuntimeException: Command run failed with code[1]: cd '/PHPAR/static-php-cli/source/zlib' && PKG_CONFIG_PATH="/PHPAR/static-php-cli/buildroot/lib/pkgconfig" CC='musl-gcc' CXX='g++' ./configure --static --prefix= 1>/dev/null 2>&1 [21:03:14] [CRIT] Please check with --debug option to see more details.

@TNT-ma build 命令也可以加上 `--debug` 查看具体报错信息。
