### ISSUE TITLE
libaom compilation broken

### ISSUE THREAD

**Issue by dunglas** [crazywhalecc/static-php-cli#577]
Hi,

FrankenPHP builds are broken because libaom compilation crashes: https://github.com/dunglas/frankenphp/actions/runs/12401722257/job/34660367231

It may be related to https://github.com/crazywhalecc/static-php-cli/pull/575 (our build was green before).

**Comment by crazywhalecc** [comment]
This only affect Alpine Linux because of missing patches: https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/main/aom/posix-implicit.patch
