### ISSUE TITLE
Contributing to patches. Where can I do this?

### ISSUE THREAD

**Issue by SRWieZ** [crazywhalecc/static-php-cli#582]
Hi! 

I fixed the PHP 8.4 Windows build for NativePHP, but I'm not sure which repository I should use to propose my patch. 

The documentation links to: https://github.com/easysoft/phpmicro, but the script uses https://github.com/static-php/phpmicro. 

I'm a [bit lost](https://github.com/easysoft/phpmicro/network) ^^

**Comment by crazywhalecc** [comment]
Because the author of the upstream repository does not have much time to review the code, I temporarily switched to the fork of static-php. If you want to apply static-php-cli as soon as possible, you can PR to the fork.

**Comment by SRWieZ** [comment]
Thanks for the clarification! Will do that!
