### ISSUE TITLE
请问如何引入ini文件呢？

### ISSUE THREAD

**Issue by ikilobyte** [crazywhalecc/static-php-cli#6]

**Comment by crazywhalecc** [comment]
下载或编译好静态 PHP 文件后，可以使用 PHP 自带的参数 `-c path/to/your/php.ini` 指定。

**Comment by ikilobyte** [comment]
感谢对php生态做出的贡献！

**Comment by ikilobyte** [comment]
看到readme里面的php.ini 内嵌或分发，使用-c是不是就可以解决了，是同一个问题吗

**Comment by crazywhalecc** [comment]
不是的，这个问题主要是没办法默认指定一个 `php.ini`，也就是直接 `./php`，面对运行不同的系统环境，它不能知道 `php.ini` 在哪，也许可以通过修改 PHP 源码来实现，但目前还没有做。

**Comment by ikilobyte** [comment]
好的，有交流群吗，或者方便加个微信吗

**Comment by crazywhalecc** [comment]
本项目暂时没有交流群，纯一个人开发，微信可能不方便直接发布到 GitHub，可以用邮件联系我。
