### ISSUE TITLE
贴个赞助二维码吧！

### ISSUE THREAD

**Issue by ikilobyte** [crazywhalecc/static-php-cli#62]
看到你们这么努力的为php生态做贡献，给本就不怎样的php增添了有一种可能，所以还是贴个赞助二维码吧，能收获一些支持也是对你们的肯定  @crazywhalecc

**Comment by crazywhalecc** [comment]
感谢支持，我一直忘记搞这些了。刚才把赞助链接的方式放在项目右边了，国际友人可以通过 Buy Me a Coffee 赞助，国内用户可以直接支付宝。
