### ISSUE TITLE
请求添加xlswriter

### ISSUE THREAD

**Issue by mmmcatoo** [crazywhalecc/static-php-cli#65]
项目地址：https://github.com/viest/php-ext-xlswriter
请求原因：导出Excel的需求很正常，常规的phpspreadsheet在面对大量数据导出的时候太慢，这个扩展处理的速度很快，很适合大包到SAPI方便调用

**Comment by crazywhalecc** [comment]
好的，近期尝试加上。

**Comment by crazywhalecc** [comment]
Supported via https://github.com/crazywhalecc/static-php-cli/commit/aa9ec6e50e1b1199557c185b215efdaa85a796f8
