### ISSUE TITLE
Error when building libxml2 in combination with intl

### ISSUE THREAD

**Issue by mpociot** [crazywhalecc/static-php-cli#68]
When building PHP with an extension that requires `libxml2` as well as `intl` the order of the extensions is important.

The `libxml2` builder checks if the icu library is available (which it is because of intl).

https://github.com/crazywhalecc/static-php-cli/blob/refactor/src/SPC/builder/macos/library/libxml2.php#L20

But if `intl` is after the xml extension in the build order, this fails because `icu` is not yet available.

This fails:

```
./bin/spc build xml,intl
```

This works:

```
./bin/spc build intl,xml
```

I think it would be good to internally change the order of some extensions when they are required. For example icu could just always be compiled first.
I'm not sure if that's already implemented somewhere.

**Comment by crazywhalecc** [comment]
Fixed via https://github.com/crazywhalecc/static-php-cli/commit/b2f3ffcc0075cda268b27617ef1c2b7a02cf72e1
