### ISSUE TITLE
如何添加自定扩展？比如swoole_loader

### ISSUE THREAD

**Issue by zhqingphp** [crazywhalecc/static-php-cli#69]
如何添加自定扩展？比如swoole_loader

**Comment by crazywhalecc** [comment]
目前 Linux 环境为纯静态编译的版本，无法添加外部没有源码的扩展，目前源码加密类的扩展均为此类，所以无法添加。

另外，macOS 因为系统特性，无法静态编译，且可装载 ffi，所以支持动态链接，甚至可以链接 xdebug 等扩展。但这不是本项目的主旨，如果有需要我会出文档。
