### ISSUE TITLE
php7.2无法构建aarch64架构的可执行文件

### ISSUE THREAD

**Issue by ikilobyte** [crazywhalecc/static-php-cli#73]
老项目使用的是7.2版本，但`refactor`不支持7.2，只能使用`bash-version`，由于 https://dl.zhamao.xin/php-bin/file/ 提供的文件有`event`扩展，项目原因需要去掉`event`扩展，所以只能重新构建，但遇到了以下问题
*  workflows构建出来的`aarch64`依然是`x86_64`
*  `sed -ie 's/alpine:latest/multiarch\/alpine:${{ matrix.arch }}-v3.16/g' Dockerfile`  这个无法替换，Dockerfile中使用的是`alpine:3.16`

**Comment by crazywhalecc** [comment]
refactor 不是不支持 7.2，只是部分扩展用最新版的话可能不支持旧版本的 PHP 了，所以明面上的文档只写了支持较新的 PHP。如果你一个扩展都不带入或者带一些很久没更新的库、一些旧版本通用的扩展进行编译（例如 mbstring）的话，那显然是可以成功的，只需要下载时候使用 `bin/spc fetch --with-php=7.2 --all` 换下版本就行了。有些扩展旧版本使用的命令可能是 enable，新版本使用的是 with，这个遇到了修改一下 SPC 源码应该也能解决。

bash-version 主要是 multiarch/alpine 的 tag 有变化，换成 `multiarch/alpine:aarch64-edge` 应该可以，但据说 edge 版本取消了某些静态编译的包，无法直接下载使用，所以可能会出现一些问题。有关 multiarch 支持的 docker tag 建议到 Docker Hub 找一下。

**Comment by jingjingxyk** [comment]
我的个人快速构建经验是： 

1、租 aarch64  架构的云服务器 
2、选择抢占式服务器  ( 因为比按量付费便宜多了，比如选择16核或者32核的 。每小时 大约 1块钱左右  ）

这样做可以快速验证 构建参数，及时调整   (github action 上使用qemu 模拟 aarch64 构建速度很慢的）

**Comment by ikilobyte** [comment]
@jingjingxyk 按照你的方法 （租 aarch64 架构的云服务器），成功把`php7.2-aarch64`编译出来了，我自己fork的仓库在github上一直构建失败，而且时间还长
