### ISSUE TITLE
使用cmake 安装的 libxml 库 需要patch 解决  buildroot/usr/bin/xml2-config 文件里的路径问题

### ISSUE THREAD

**Issue by jingjingxyk** [crazywhalecc/static-php-cli#75]
验证发现  文件 `buildroot/usr/bin/xml2-config`  里面包含的目录不正确

`cd  buildroot/usr/bin/  `
`./xml2-config --libs`
 `./xml2-config --cflags`

上述返回的结果是不正确的

vi   buildroot/usr/bin/xml2-config 
```text
#! /bin/sh

prefix=$(cd "$(dirname "$0")"; pwd -P)/..

```

只需要修改这个文件：https://github.com/jingjingxyk/static-php-cli/blob/feature_pgsql/src/SPC/builder/unix/library/libxml2.php

解决办法一： 指定安装目录

```shell 

#   把此行  
"{$this->builder->makeCmakeArgs()} " .  

#  替换为
   "-DCMAKE_INSTALL_PREFIX={$destdir} " .


```

解决办法二：替换xml2-config  文件内容

```shelll
      # 最后新增三行
      $realpath = $destdir . '/usr/bin/xml2-config';
      $file = FileSystem::readFile($realpath);
      $file = preg_replace('/^prefix=.*$/m', 'prefix=' . BUILD_ROOT_PATH, $file);
      FileSystem::writeFile($realpath, $file);

```

**Comment by crazywhalecc** [comment]
方案一正解。我记得至少有一个使用 cmake 的库，我没有直接使用 `makeCmakeArgs()` 方法，毕竟这个只是个复用代码的方法，特殊情况完全可以不用的，能少 patch 就尽量少 patch。
