### ISSUE TITLE
为啥pkg-config 也要用源码编译？

### ISSUE THREAD

**Issue by jingjingxyk** [crazywhalecc/static-php-cli#76]

**Comment by crazywhalecc** [comment]
因为直接使用不同系统环境下的 pkg-config 会导致某些情况还是使用了系统库进行编译，因为 pkg-config 除了识别 `PKG_CONFIG_PATH` 变量之外，内部在编译的时候也有参数指定一些默认的位置，例如 `/usr` 等，而寻找逻辑是自动 fallback 的，这对用户态编译的 static-php-cli 来说是无法控制的，所以不得不手动编译 pkg-config 来让所依赖的库和 PHP 使用。

当然也有一种原始的解决方案，就是卸载原系统的库，但这样会入侵破坏系统环境。之前你也知道不是没有尝试过不使用 pkg-config 直接指定 XXX_LIBS 的硬核方式，最后决定继续利用 pkg-config。

**Comment by jingjingxyk** [comment]
实际是需要这两种 `XXX_LIBS`   和  `pkg-config ` 混合使用  
原因：在于制作扩展灵活度很高,编译时扩展接受参数方式不一样

**Comment by jingjingxyk** [comment]
关键点,这样就搞定了  https://github.com/jingjingxyk/static-php-cli/blob/736c9ab35c72c83c0998705e6976313dbdfee490/src/SPC/builder/linux/LinuxBuilder.php#L170C1-L170C1

https://github.com/jingjingxyk/static-php-cli/blob/736c9ab35c72c83c0998705e6976313dbdfee490/src/SPC/builder/unix/library/postgresql.php#L22


```php
        $env = $this->builder->configure_env;
        $packages = 'openssl zlib icu-uc icu-io icu-i18n readline libxml-2.0 libzstd';
        $output = shell()->execWithResult($env . ' pkg-config      --libs-only-l   --static  ' . $packages);
        $libs = $output[1][0];
        $env .= " CPPFLAGS=\"-I{$builddir}/include/\" ";
        $env .= " LDFLAGS=\"-L{$builddir}/lib/\" ";
        $env .= " LIBS=\"{$libs}\" ";

```
