### ISSUE TITLE
How to compile with a PHAR?

### ISSUE THREAD

**Issue by wesmontgomery** [crazywhalecc/static-php-cli#8]
I want to compile PHP and a PHAR together as a single application. How would this be possible?

Looking to use something like [box](https://github.com/box-project/box):

https://github.com/box-project/box/issues/331

**Comment by crazywhalecc** [comment]
Making PHP binary and PHP code together is a good issue, and this project can build an single php static binary file with extensions but not single application with code.

I saw a repo <https://github.com/dixyes/phpmicro>, this can patch the php source to achieve this, but I haven't tried it. Maybe it can integrate with static-php-cli project.

**Comment by crazywhalecc** [comment]
I made it, and built a single file application!

**Comment by crazywhalecc** [comment]
Solved. You can follow README to download or compile micro and put code and php binary together.

**Comment by wesmontgomery** [comment]
Thank you! Will try this out soon
