### ISSUE TITLE
需要主流的各种数据库扩展

### ISSUE THREAD

**Issue by TimeIsGoOn** [crazywhalecc/static-php-cli#80]
你好，希望能提供主流的各种数据库扩展，比如 postgresql ，  sqlserver ， Oracle 这些。 
业务上还挺常用的。

**Comment by crazywhalecc** [comment]
postgresql 已经在调试了，需要稳定编译后会上。见：#60
sqlserver 和 oracle 因为官方的库不是开源的且没有一个不依赖闭源库的完整开源扩展，目前无法直接在 Linux 环境下使用并编译，只能使用动态连接的形式，见：#52
