### ISSUE TITLE
计划把 patch pkgconfig 去掉

### ISSUE THREAD

**Issue by jingjingxyk** [crazywhalecc/static-php-cli#83]
原因： patch pkgconfig 替换路径，存在很大问题，导致找不到正确的头文件，以及，如若头文件名称相同，直接就被覆盖了

![image](https://github.com/crazywhalecc/static-php-cli/assets/6836228/2ec638e9-e7da-45fa-8cce-2cae507d07e4)
比如检测curl 头文件，正常时在 include/curl/ 目录下，替换以后直接就在 include 目录下了。会出现找找不到

正常应该如下图： 
![image](https://github.com/crazywhalecc/static-php-cli/assets/6836228/5a787e32-1f28-4826-8c4e-f9a4a70f796a)

**Comment by jingjingxyk** [comment]
@crazywhalecc  这不是需不需要的问题啊，而是需要的时候，没有。
看例子： libpq源码里 引用 openssl  。直接引用的是 openssl/ssl.h 
vi src/include/libpq/libpq-be.h
```c
#ifdef USE_OPENSSL
#include <openssl/ssl.h>
#include <openssl/err.h>
```

![image](https://github.com/crazywhalecc/static-php-cli/assets/6836228/2445b251-ae8a-4fde-a56d-8ee73c38cd9b)

**Comment by crazywhalecc** [comment]
我没有搞懂你说的意思。你是说有的库的 .h 文件不能被 pkgconfig 内提供的参数覆盖吗？而且即使是你提到的这个 openssl 和 libxml2 的问题其实是不存在的，例如引入 openssl 时 Cflag 就是 `-I"buildroot/include"` 目录，在编译时使用 `#include <openssl/ssl.h>` 就会自动寻找 `buildroot/include/openssl/ssl.h` 这个文件，并不存在你说的引用问题，而且其他库都是这么引用的，例如 curl：`#if defined(USE_OPENSSL) #  include <openssl/ssl.h>`。

**Comment by jingjingxyk** [comment]
@crazywhalecc  需求就是把这个 https://github.com/crazywhalecc/static-php-cli/pull/84  跑起来，不想要 patch   ，也不想添加其他代码  

当前状况是，如果不修改其他库，构建PGSQL 预处理都都跑不起来。第一步需要解决xml2-config ，然后是libzstd

**Comment by jingjingxyk** [comment]
去掉大部分 PATCH 的关键代码： 包括curl 的patch 
```PHP

        $builddir = BUILD_ROOT_PATH;
        $cppflags = '';
        $ldflags = '';
        $libs = '';

        if (!empty($this->pkg_config_packages)) {
            $packages = implode(' ', $this->pkg_config_packages);
            $output = shell()->execWithResult($envs . ' pkg-config      --libs-only-l   --static  ' . $packages);
            if (!empty($output[1][0])) {
                $libs = $output[1][0];
                logger()->info('LIBS=' . $output[1][0]);
            }
            $output = shell()->execWithResult($envs . ' pkg-config      --cflags-only-I   --static  ' . $packages);
            if (!empty($output[1][0])) {
                $cppflags = $output[1][0];
                logger()->info('CPPFLAGS=' . $output[1][0]);
            }
            $output = shell()->execWithResult($envs . ' pkg-config      --libs-only-L   --static  ' . $packages);
            if (!empty($output[1][0])) {
                $ldflags = $output[1][0];
                logger()->info('LDFLAGS=' . $output[1][0]);
            }
        }
        if ($this->getLib('libiconv')) {
            $libs .= ' -liconv ';
        }
        if ($this->getLib('bzip2')) {
            $libs .= ' -lbz2';
        }
        if ($this->getLib('icu')) {
            $libs .= ' -lstdc++';
        }

        $envs .= " CPPFLAGS=\"-I{$builddir}/include/ {$cppflags}\" ";
        $envs .= " LDFLAGS=\"-L{$builddir}/lib/  {$ldflags}\" ";
        if (!empty($libs)) {
            $envs .= " LIBS=\"{$libs} \" ";
        }

        if (!empty(trim($cflags))) {
            $envs .= " CFLAGS='{$cflags} ";
        }

```

https://github.com/jingjingxyk/static-php-cli/blob/main/src/SPC/builder/linux/LinuxBuilder.php#L160

https://github.com/jingjingxyk/static-php-cli/blob/main/src/SPC/builder/unix/library/curl.php (cmake 默认链接都是动态库，使用package_name_ROOT 参数，申明静态库位置）

**Comment by crazywhalecc** [comment]
>  (cmake 默认链接都是动态库，使用package_name_ROOT 参数，申明静态库位置）

这里应该不存在这个问题。首先自编译的 pkg-config 可以限定库只从 buildroot 查找，其次输入的 cmake toolchain file 中也描述了只在指定的根目录下查找包，而 buildroot 只有静态库，所以不会连接到动态库。
