### ISSUE TITLE
可用这三个 LIBS CPPFLAGS LDFLAGS  编译参完全替换 构建PHP 用到的这三个EXTRA_CFLAGS  EXTRA_LIBS   EXTRA_LDFLAGS_PROGRAM 参数

### ISSUE THREAD

**Issue by jingjingxyk** [crazywhalecc/static-php-cli#86]
替换前
```php
    shell()->cd(SOURCE_PATH . '/php-src')
        ->exec('sed -i "s|//lib|/lib|g" Makefile')
        ->exec(
            'make -j' . $this->concurrency .
            ' EXTRA_CFLAGS="-g -Os -fno-ident ' . implode(' ', array_map(fn ($x) => "-Xcompiler {$x}", $this->tune_c_flags)) . '" ' .
            "EXTRA_LIBS=\"{$extra_libs}\" " .
            "EXTRA_LDFLAGS_PROGRAM='{$use_lld} -all-static' " .
            'cli'
        );

```

替换后
```php

   shell()->cd(SOURCE_PATH . '/php-src')
            ->exec($envs . ' make -j ' . $this->concurrency . ' cli ');


```

详细： https://github.com/jingjingxyk/static-php-cli/blob/8af7ac9c554a2ac78492a96e583c1bd61b4f1aa2/src/SPC/builder/linux/LinuxBuilder.php#L284

**Comment by crazywhalecc** [comment]
替换目标在哪里？

**Comment by jingjingxyk** [comment]
能解决很多，很多问题，比如swoole 编译，比如cares 库（异步DNS）。连没有pkg-config 配置的库，也可以解决

**Comment by jingjingxyk** [comment]
也就是用这三个参数： LIBS CPPFLAGS LDFLAGS  编译参数来解决遇到的问题

相见这个文件：https://github.com/jingjingxyk/static-php-cli/blob/feature_use_pkg-config/src/SPC/builder/linux/LinuxBuilder.php

174行开始

**Comment by crazywhalecc** [comment]
这个方式有用，但目前确实不方便将所有扩展改为这种方式。理由有下：

1. 目前的形式基本上是基于独立的 lib 编译和最终的 php 编译引入 extra_libs 形式，改变这样的形式在未来适配 glibc 链接时需要考虑的改动比较多。
2. 使用 `LIBS`、`CPPFLAGS`、`LDFLAGS` 有时候并不是最终需要的结果，而且这样需要多记录一层 pkg-config 的文件名，我们已经记录了所有库的 `.a` 库，似乎是重复的。
3. 如果有依赖库需要这种形式，可以单独使用，例如你贡献的 postgresql 依赖和相关扩展，和现有逻辑不冲突。
