### ISSUE TITLE
/usr/include/c++/10/condition_variable:209: undefined reference to `pthread_cond_clockwait'

### ISSUE THREAD

**Issue by jingjingxyk** [crazywhalecc/static-php-cli#87]
debian 11 环境下   musl-gcc 编译器

编译swoole 扩展时： 
```shell

l2 -lxml2 -lz -lssl -lcrypto  -o sapi/cli/php
/usr/bin/ld: ext/swoole/src/os/async_thread.o: in function `std::cv_status std::condition_variable::__wait_until_impl<std::chrono::duration<long, std::ratio<1l, 1000000000l> > >(std::unique_lock<std::mutex>&, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const&)':
/usr/include/c++/10/condition_variable:209: undefined reference to `pthread_cond_clockwait'


```

![image](https://github.com/crazywhalecc/static-php-cli/assets/6836228/0a51471f-1064-4458-a247-b14d9c4ac98a)

添加 -lpthread 并不生效，猜问题所在：  glibc 和 libc 函数不兼容

**Comment by jingjingxyk** [comment]
通过验证： 编译swoole ，可用编译组合：  `--cc=clang --cxx=clang++ --debug`  和  `--cc=clang --cxx=clang++ --debug`

swow  可以使用  `--cc=musl-gcc --cxx=g++ --debug` 编译成功

**Comment by crazywhalecc** [comment]
目前我无法在 Debian 环境下通过直接指定编译器来编译成功 Swoole 等依赖 C++ 的库。有什么其他需要修改的地方吗？

**Comment by jingjingxyk** [comment]
我是用LIBS CPPFLAGS LDFLAGS 编译参数解决的。

https://github.com/crazywhalecc/static-php-cli/issues/86#issuecomment-1637335319
