### ISSUE TITLE
使用cmake 编译 curl 库，需要 规避curl 这个bug 

### ISSUE THREAD

**Issue by jingjingxyk** [crazywhalecc/static-php-cli#88]
当在debian 环境 使用 musl-cc 或者 clang 时会出现这个问题。alpine 环境下没有这个问题

curl bug  信息：[-lgcc -lgcc_s -lc -lgcc -lgcc_s](https://github.com/curl/curl/issues/6167) 

https://github.com/curl/curl/blob/29f33b3400431e23afc85d6ec23427864104d730/docs/KNOWN_BUGS#L527

解决办法：
```shell
 shell()->cd($this->source_dir)
            ->exec('sed -i.save s@\${CMAKE_C_IMPLICIT_LINK_LIBRARIES}@@ CMakeLists.txt');

````

**Comment by crazywhalecc** [comment]
有具体的说明或解决方案吗，替换了目前对现有编译有无影响？

**Comment by jingjingxyk** [comment]
上述结论是通过实践的得到结果。 是为了解决问题。

比如我在debian 环境下，用clang 编译，肯定是使用pkg-config 才发现的这个问题，不使用pkg-config 是不会触发这个问题。


验证，是通过quickstart 里面的脚本，把 OS 切换为 debian 即可开始验证。
