### ISSUE TITLE
可以安装protobuf扩展吗

### ISSUE THREAD

**Issue by ikilobyte** [crazywhalecc/static-php-cli#9]

**Comment by crazywhalecc** [comment]
可以，但需要 patch 一下，同时本仓库主线将默认不会对该扩展编译安装，下一个版本会发布支持 protobuf 安装，但需要自行从 Docker 构建，并在构建时弹出的扩展选择菜单中用空格选择 `protobuf` 即可。

**Comment by ikilobyte** [comment]
好的，感谢

**Comment by crazywhalecc** [comment]
Added via https://github.com/crazywhalecc/static-php-cli/commit/4c55f4a22be0b2e130af023ef7593bcefa78314a
