### ISSUE TITLE
Actions构建问题：gmplib

### ISSUE THREAD

**Issue by loyating** [crazywhalecc/static-php-cli#90]
[gmplib官网说明](https://gmplib.org/)
> NEWS 2023-06-21: The GMP servers has been under serious load due to a barrage of clone requests from Microsoft/Github. Github's setup encourages "forks" of their projects, and such forks then by default pull in parent project changes. Around 2023-06-15, a project known as FFmpeg decided that it would be a great idea to clone GMP in their CI scripts, meaning that every one of their commits requested a compressed clone from the GMP servers. But, by Github's design, hundreds of FFmpeg forks automatically followed suit, themselves cloning the GMP repo.
In effect, Microsoft's computer cloud performed a DDoS attack on the GMP servers.
After bringing up the issue here and on the GMP mailing lists, some Github brass replied, minimizing the issue and blaming our servers for the denial-of-service attack. They did not do anything to stop the attack! In fact, it is still ongoing a week later.
Our servers are fully available again, but that's the result of us adding all participating Microsoft network ranges to our firewall. We understand that we are far from the first project to take such measures against Github.

[curl: (28) Failed to connect to gmplib.org port 443 after 130673 ms: Connection timed out](https://github.com/loyating/static-php-cli/actions/runs/5471473853/jobs/9962649274#step:11:147)

**Comment by jingjingxyk** [comment]
这问题很久之前就遇到了。只不过大伙视而不见而已。 同时对于解决方法也是嗤之以鼻。镜像存在信任问题

解决办法就是，建立依赖库源码包镜像，使用镜像分发。 （对于本项目，因为拉取的包是最新版本，建立镜像，需要保持源码包最新）


相见解决办法实践： https://github.com/jingjingxyk/swoole-cli/tree/main/sapi/download-box


最好的解决办法就是：
   使用  ghcr.io 容器镜像分发（把源码包，打包到容器镜像内），用的时候，直接拉去 ghcr.io 容器镜像。从容器中拷贝出来源码包

**Comment by crazywhalecc** [comment]
Fixed via https://github.com/crazywhalecc/static-php-cli/commit/7d31c371e099010a48c99276c126d58d09a00ec9
