### ISSUE TITLE
拉依赖库比较慢，能否指定下载源啊？

### ISSUE THREAD

**Issue by wensenz** [crazywhalecc/static-php-cli#92]
./bin/spc fetch --all

**Comment by crazywhalecc** [comment]
如果是本地构建，可以从 GitHub 提前下载最近一次的 Actions 打包的 downloads 目录，并解压使用。但目前由于 fetch 直接从官方下载，无法直接切换镜像站（而且部分资源没有镜像站支持），所以无法指定下载源。

中国大陆用户更建议使用代理等方式下载，下载后不需要每次下载可反复使用。

**Comment by wensenz** [comment]
> 

这个Actions包的具体下载地址是？

**Comment by crazywhalecc** [comment]
@wensenz https://github.com/crazywhalecc/static-php-cli/actions/runs/5117916508

**Comment by wensenz** [comment]
没有找到linux 版本的 8.1.的依赖

**Comment by crazywhalecc** [comment]
看下来这个链接问题现在没有一个好的解决方案，而且官方源也有可能自身有限制而无法做到 100% 成功访问。我后续会加一个指定对应资源使用对应的下载方式的控制台参数，例如：`export SPC_CUSTOM_PHP_URL="https://www.example.com/php.tar.gz" ; ./bin/spc download --all`，同时后续会给一个推荐的镜像下载资源的列表。

**Comment by jingjingxyk** [comment]
可以这样哈： 

```shell
mkdir -p download-box
cd download-box

curl -Lo download-box-get-archive-from-container.sh   https://github.com/jingjingxyk/static-php-cli/blob/feature_use_pkg-config/download-box/download-box-get-archive-from-container.sh?raw=true

bash download-box-get-archive-from-container.sh

```

原理和代码： https://github.com/jingjingxyk/static-php-cli/tree/feature_use_pkg-config/download-box


用镜像最大的问题，是信任问题，解决这个问题的办法是 hash 校验

**Comment by wensenz** [comment]
我用本地的macOs ， 试了下， 下载到downloads也不行， 提示
<img width="699" alt="image" src="https://github.com/crazywhalecc/static-php-cli/assets/10190672/ced15bfa-7ad3-4a18-ad92-2f84197cf22a">
这个是我的download目录：
<img width="870" alt="image" src="https://github.com/crazywhalecc/static-php-cli/assets/10190672/29e468b9-676b-4c20-9102-f5085c75f9f7">

**Comment by wensenz** [comment]
并且我用wget下载好都不行，还把我wget下载的文件删除了
<img width="1370" alt="image" src="https://github.com/crazywhalecc/static-php-cli/assets/10190672/44a2eb3c-6613-4e93-869b-4de48d890749">

**Comment by crazywhalecc** [comment]
貌似我很长时间没有构建 CI 了，CI 里面可能没有包含所有库，我近期再手动更新一下。

这个下载包的事情，我后续根据上面的建议和我的想法更新一下，这确实是个问题。

**Comment by wensenz** [comment]
最终通过代理解决了， 还是🪜好用

**Comment by crazywhalecc** [comment]
目前新增了一个每周五自动打包 downloads 目录的 Workflow，可以点进去选最新成功的执行下载对应 PHP 版本的 downloads 目录。https://github.com/crazywhalecc/static-php-cli/actions/workflows/download-cache.yml

**Comment by crazywhalecc** [comment]
目前又加了一个可以直接指定 download zip 文件的命令参数 `--from-zip`，可以直接手动从 GitHub Action 下载好 `download.zip` 后，使用命令 `bin/spc download --from-zip /path/to/your/download.zip` 即可直接将 zip 解压到 downloads 并使用。

**Comment by crazywhalecc** [comment]
最新的 commit 添加了 `-U` 下载指令，如果有些包下载比较慢想切为镜像地址，或者想下载测试版，可以使用这个参数指定下载地址，例如：`bin/spc download --all -U "php-src:https://mirrors.zhamao.xin/php/php-8.2.8.tar.gz"`。
